In [ ]:
pip install ai4bharat-transliteration

In [ ]:
pip install google-generativeai

In [ ]:
pip install transformers

In [ ]:
pip install python-dotenv

In [1]:
import pandas as pd
import re
# from ai4bharat.transliteration import XlitEngine
from dotenv import load_dotenv
load_dotenv()
import  os
# os.environ['GOOGLE_API_KEY'] = 'AIzaSyDbUB7yRW7P5Z6G1Py_sd7gakehP0e2L8Y'
import pathlib
import textwrap
from IPython.display import display
from IPython.display import Markdown
import google.generativeai as genai
# from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
genai.configure(api_key = os.getenv('GOOGLE_API_KEY'))

/home/user/anaconda3/envs/radha/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [67]:
f = open("/home/user/Documents/GENARATIVE_AI/WHAT'SAPP _CHAT_ANALYZER/dataset/WhatsApp Chat with Jyo👀🔥.....txt",'r',encoding='utf-8')

In [68]:
data = f.read()

In [69]:
data

'9/5/23, 21:29 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n9/9/23, 01:07 - Naga Siva Sai Prasanth: <Media omitted>\n9/9/23, 01:19 - Naga Siva Sai Prasanth: <Media omitted>\n9/9/23, 22:29 - Jyo👀🔥....: <Media omitted>\n9/12/23, 01:23 - Jyo👀🔥....: <Media omitted>\n9/12/23, 01:57 - Jyo👀🔥....: <Media omitted>\n9/14/23, 21:59 - Naga Siva Sai Prasanth: <Media omitted>\n9/19/23, 03:27 - Jyo👀🔥....: <Media omitted>\n9/19/23, 22:26 - Naga Siva Sai Prasanth: <Media omitted>\n9/21/23, 18:45 - Naga Siva Sai Prasanth: <Media omitted>\n9/24/23, 17:06 - Jyo👀🔥....: <Media omitted>\n9/25/23, 05:01 - Jyo👀🔥....: <Media omitted>\n9/25/23, 05:05 - Jyo👀🔥....: <Media omitted>\n9/25/23, 05:12 - Jyo👀🔥....: <Media omitted>\n9/26/23, 01:55 - Naga Siva Sai Prasanth: <Media omitted>\n10/3/23, 23:28 - Jyo👀🔥....: <Media omitted>\n10/4/23, 15:05 - Jyo👀🔥....: <Media omitted>\n10/4/23, 22:07 - Naga Siva Sai Prasanth: <Media omitted>\n10/4/23, 22:07 - Naga Siva Sai Prasanth: <Media omitted>\n10/4/23, 22:07 - Naga Siva Sai Prasanth: <Media omitted>\n10/4/23, 22:07 - Naga Siva Sai Prasanth: <Media omitted>\n10/4/23, 22:39 - Naga Siva Sai Prasanth: <Media omitted>\n10/4/23, 22:40 - Jyo👀🔥....: <Media omitted>\n10/4/23, 23:04 - Naga Siva Sai Prasanth: <Media omitted>\n10/4/23, 23:04 - Naga Siva Sai Prasanth: <Media omitted>\n10/4/23, 23:04 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 00:11 - Jyo👀🔥....: <Media omitted>\n10/5/23, 21:07 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 22:18 - Jyo👀🔥....: <Media omitted>\n10/5/23, 22:24 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 22:28 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:03 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:10 - Naga Siva Sai Prasanth: <Media omitted>\n10/5/23, 23:29 - Jyo👀🔥....: <Media omitted>\n10/6/23, 08:20 - Jyo👀🔥....: <Media omitted>\n10/6/23, 08:20 - Jyo👀🔥....: <Media omitted>\n10/6/23, 17:19 - Jyo👀🔥....: <Media omitted>\n10/8/23, 22:46 - Naga Siva Sai Prasanth: <Media omitted>\n10/8/23, 22:50 - Jyo👀🔥....: <Media omitted>\n10/9/23, 12:03 - Jyo👀🔥....: <Media omitted>\n10/11/23, 00:12 - Jyo👀🔥....: <Media omitted>\n10/15/23, 15:44 - Jyo👀🔥....: <Media omitted>\n10/15/23, 15:44 - Jyo👀🔥....: <Media omitted>\n10/15/23, 15:44 - Jyo👀🔥....: <Media omitted>\n10/17/23, 20:04 - Jyo👀🔥....: <Media omitted>\n10/18/23, 13:35 - Jyo👀🔥....: <Media omitted>\n10/18/23, 21:57 - Jyo👀🔥....: <Media omitted>\n11/13/23, 17:46 - Jyo👀🔥....: <Media omitted>\n11/13/23, 17:46 - Jyo👀🔥....: <Media omitted>\n11/13/23, 17:46 - Jyo👀🔥....: <Media omitted>\n11/13/23, 17:46 - Jyo👀🔥....: <Media omitted>\n11/13/23, 17:46 - Jyo👀🔥....: <Media omitted>\n11/13/23, 17:46 - Jyo👀🔥....: <Media omitted>\n11/13/23, 17:46 - Jyo👀🔥....: <Media omitted>\n11/18/23, 23:01 - Jyo👀🔥....: <Media omitted>\n11/24/23, 09:21 - Jyo👀🔥....: <Media omitted>\n12/23/23, 15:54 - Naga Siva Sai Prasanth: null\n12/23/23, 17:16 - Jyo👀🔥....: null\n12/23/23, 17:50 - Jyo👀🔥....: null\n12/23/23, 17:53 - Naga Siva Sai Prasanth: null\n12/23/23, 23:04 - Jyo👀🔥....: null\n12/23/23, 23:04 - Jyo👀🔥....: null\n12/23/23, 23:09 - Jyo👀🔥....: null\n12/23/23, 23:09 - Jyo👀🔥....: null\n12/23/23, 23:10 - Jyo👀🔥....: null\n12/23/23, 23:15 - Jyo👀🔥....: null\n12/24/23, 21:39 - Jyo👀🔥....: null\n12/24/23, 22:36 - Jyo👀🔥....: null\n12/24/23, 22:36 - Jyo👀🔥....: null\n12/24/23, 22:39 - Jyo👀🔥....: null\n12/24/23, 22:39 - Jyo👀🔥....: null\n12/25/23, 13:28 - Naga Siva Sai Prasanth: null\n12/26/23, 00:58 - Naga Siva Sai Prasanth: null\n12/26/23, 00:59 - Naga Siva Sai Prasanth: null\n12/26/23, 00:59 - Naga Siva Sai Prasanth: null\n12/26/23, 00:59 - Naga Siva Sai Prasanth: null\n12/26/23, 17:15 - Jyo👀🔥....: null\n12/26/23, 17:16 - Jyo👀🔥....: null\n12/26/23, 17:17 - Jyo👀🔥....: null\n12/26/23, 17:17 - Jyo👀🔥....: null\n12/26/23, 17:17 - Jyo👀🔥....: null\n12/26/23, 17:17 - Jyo👀🔥....: null\n12/26/23, 21:40 - Naga Siva Sai Prasanth: null\n12/27/23, 11:06 - Naga Siva Sai Prasanth: null\n12/27/23, 11:41 - Jyo👀🔥....: null\n12/27/23, 11:42 - Naga Siva Sai Prasanth: null\n12/27/23, 11:43 - Naga Siva Sai Prasanth: null\n12/27/23, 11:43 - Naga Siva Sai Prasanth: null\n12/27/23, 11:43 - Naga Siva Sai Prasanth: null\n12/27/23, 11:44 - Naga Siva Sai Prasanth: null\n12/27/23, 11:44 - Naga Siva Sai Prasanth: null\n12/27/23, 21:33 - Jyo👀🔥....: <Media omitted>\n12/27/23, 21:33 - Jyo👀🔥....: <Media omitted>\n12/27/23, 21:33 - Jyo👀🔥....: <Media omitted>\n12/27/23, 21:34 - Jyo👀🔥....: <Media omitted>\n12/27/23, 21:34 - Jyo👀🔥....: <Media omitted>\n12/27/23, 21:34 - Jyo👀🔥....: <Media omitted>\n12/27/23, 21:36 - Naga Siva Sai Prasanth: Ok\n12/27/23, 21:36 - Jyo👀🔥....: Nedhi aipoyaka\n12/27/23, 21:36 - Jyo👀🔥....: Naku cheppu maths..\n4th chapter\n12/27/23, 21:37 - Jyo👀🔥....: Okay na...\nMarchipoku raa nanaa\n12/27/23, 22:12 - Naga Siva Sai Prasanth: null\n12/27/23, 22:47 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 00:03 - Jyo👀🔥....: Hello\n12/28/23, 00:03 - Jyo👀🔥....: Good morninguu\n12/28/23, 00:13 - Naga Siva Sai Prasanth: Good morningu\n12/28/23, 00:14 - Jyo👀🔥....: Doubts adugudhamani ankunnanu\n12/28/23, 00:14 - Naga Siva Sai Prasanth: Ossey\n12/28/23, 00:14 - Jyo👀🔥....: ippudu antha intrest Ledhu ra naku\n12/28/23, 00:15 - Jyo👀🔥....: ippudem adaganle\n12/28/23, 00:15 - Naga Siva Sai Prasanth: Haiga\n12/28/23, 00:15 - Naga Siva Sai Prasanth: Vachinavi\n12/28/23, 00:15 - Naga Siva Sai Prasanth: Rasi\n12/28/23, 00:15 - Naga Siva Sai Prasanth: Raa.\n12/28/23, 00:15 - Jyo👀🔥....: naku gauss forward method meedha problems\n12/28/23, 00:16 - Jyo👀🔥....: naku pics pettu\n12/28/23, 00:16 - Jyo👀🔥....: mrng oka sari chustha\n12/28/23, 00:16 - Jyo👀🔥....: inka nak opika ledhu\n12/28/23, 00:16 - Naga Siva Sai Prasanth: Mrng lepu\n12/28/23, 00:16 - Naga Siva Sai Prasanth: Pedutha\n12/28/23, 00:16 - Jyo👀🔥....: leputhanle\n12/28/23, 00:16 - Jyo👀🔥....: ennintiki\n12/28/23, 00:16 - Naga Siva Sai Prasanth: Okay..\n12/28/23, 00:16 - Naga Siva Sai Prasanth: 6\n12/28/23, 00:16 - Jyo👀🔥....: okay\n12/28/23, 00:16 - Jyo👀🔥....: ippudu pettochu ga\n12/28/23, 00:17 - Jyo👀🔥....: sare….nek velainapppudu pettu mrng lopu\n12/28/23, 00:17 - Jyo👀🔥....: chuskunta\n12/28/23, 00:18 - Naga Siva Sai Prasanth: Ok\n12/28/23, 00:18 - Naga Siva Sai Prasanth: Jyo..\n12/28/23, 00:18 - Jyo👀🔥....: Good nightuu prashu baabu\n12/28/23, 00:18 - Naga Siva Sai Prasanth: null\n12/28/23, 00:29 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 00:29 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 00:29 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 12:36 - Naga Siva Sai Prasanth: ❣️❣️\n12/28/23, 13:33 - Naga Siva Sai Prasanth: Good bye\n12/28/23, 13:33 - Naga Siva Sai Prasanth: Vey. .\n12/28/23, 13:33 - Naga Siva Sai Prasanth: Nenu hurt avina\n12/28/23, 13:33 - Naga Siva Sai Prasanth: Inka no calls\n12/28/23, 13:33 - Naga Siva Sai Prasanth: null\n12/28/23, 13:34 - Naga Siva Sai Prasanth: null\n12/28/23, 13:35 - Naga Siva Sai Prasanth: null\n12/28/23, 13:36 - Naga Siva Sai Prasanth: null\n12/28/23, 13:36 - Naga Siva Sai Prasanth: null\n12/28/23, 15:19 - Jyo👀🔥....: Em raaa\n12/28/23, 15:19 - Jyo👀🔥....: Prashu baabu\n12/28/23, 15:19 - Naga Siva Sai Prasanth: Anthae\n12/28/23, 15:19 - Naga Siva Sai Prasanth: Mari inka\n12/28/23, 15:19 - Naga Siva Sai Prasanth: Hurted\n12/28/23, 15:19 - Jyo👀🔥....: Emaindhi\n12/28/23, 15:19 - Jyo👀🔥....: Malli\n12/28/23, 15:19 - Naga Siva Sai Prasanth: Break up\n12/28/23, 15:19 - Naga Siva Sai Prasanth: U and me\n12/28/23, 15:20 - Naga Siva Sai Prasanth: Bye baby inka\n12/28/23, 15:20 - Jyo👀🔥....: No..no....no <This message was edited>\n12/28/23, 15:20 - Jyo👀🔥....: Ala cheppaku\n12/28/23, 15:21 - Naga Siva Sai Prasanth: Alane\n12/28/23, 15:21 - Naga Siva Sai Prasanth: Chebutha\n12/28/23, 15:21 - Naga Siva Sai Prasanth: Inka bye baby neku..\n12/28/23, 15:21 - Jyo👀🔥....: No...no\n12/28/23, 15:21 - Jyo👀🔥....: Arey....evng\n12/28/23, 15:21 - Naga Siva Sai Prasanth: Tffr sry for\n12/28/23, 15:21 - Naga Siva Sai Prasanth: Disturbing\n12/28/23, 15:21 - Jyo👀🔥....: 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻\n12/28/23, 15:22 - Naga Siva Sai Prasanth: Sadvukoo\n12/28/23, 15:22 - Jyo👀🔥....: Tffr anaku ra baabu\n12/28/23, 15:22 - Naga Siva Sai Prasanth: Nijjamu\n12/28/23, 15:22 - Naga Siva Sai Prasanth: Ga\n12/28/23, 15:22 - Jyo👀🔥....: Sadavdaniki raledhule...nenu\n12/28/23, 15:22 - Naga Siva Sai Prasanth: Adhukee\n12/28/23, 15:22 - Jyo👀🔥....: Oorke vacha...\nEvng varku undi velipodham ani\n12/28/23, 15:22 - Naga Siva Sai Prasanth: Sollu chepaku\n12/28/23, 15:22 - Naga Siva Sai Prasanth: Ala\n12/28/23, 15:22 - Jyo👀🔥....: Evng order vasthadhi\n12/28/23, 15:22 - Jyo👀🔥....: Adhi collect cheskuni podham ani\n12/28/23, 15:22 - Naga Siva Sai Prasanth: Chee\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Order ki\n12/28/23, 15:23 - Jyo👀🔥....: 🤦🏻\u200d♀️🤦🏻\u200d♀️🤦🏻\u200d♀️\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Nanu ramani\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Kooda\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Analedu\n12/28/23, 15:23 - Jyo👀🔥....: ....\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Nuv oka danivi\n12/28/23, 15:23 - Jyo👀🔥....: Cheppelopu aagithunnavaa\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Velutunavu\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Good bye. .\n12/28/23, 15:23 - Naga Siva Sai Prasanth: Cover up..\n12/28/23, 15:23 - Jyo👀🔥....: Chepthunte...\n12/28/23, 15:24 - Jyo👀🔥....: Nijam ra...start chesa...evng ani...elopu topper saduko antunnav\n12/28/23, 15:24 - Naga Siva Sai Prasanth: Sollu\n12/28/23, 15:24 - Naga Siva Sai Prasanth: Good bye\n12/28/23, 15:24 - Naga Siva Sai Prasanth: Neku naku\n12/28/23, 15:24 - Jyo👀🔥....: Chat chaduvu\n12/28/23, 15:24 - Jyo👀🔥....: Okasari\n12/28/23, 15:25 - Jyo👀🔥....: Sachinodaa\n12/28/23, 15:25 - Naga Siva Sai Prasanth: Matalu levu\n12/28/23, 15:25 - Naga Siva Sai Prasanth: Inka\n12/28/23, 15:25 - Jyo👀🔥....: Raavaa....?\n12/28/23, 15:25 - Naga Siva Sai Prasanth: Neku cutted\n12/28/23, 15:25 - Naga Siva Sai Prasanth: Inka neku naku\n12/28/23, 15:25 - Jyo👀🔥....: No\n12/28/23, 15:25 - Naga Siva Sai Prasanth: No blood relations\n12/28/23, 15:25 - Jyo👀🔥....: Muskuni raa anthe\n12/28/23, 15:25 - Jyo👀🔥....: Avnu le\nBlood relation ledhu\n12/28/23, 15:25 - Naga Siva Sai Prasanth: Chii\n12/28/23, 15:26 - Naga Siva Sai Prasanth: Ekada kooda\n12/28/23, 15:26 - Naga Siva Sai Prasanth: Ledhu ani\n12/28/23, 15:26 - Naga Siva Sai Prasanth: Chepinavu\n12/28/23, 15:26 - Naga Siva Sai Prasanth: Nanu\n12/28/23, 15:26 - Naga Siva Sai Prasanth: Veru chesi\n12/28/23, 15:26 - Jyo👀🔥....: Blood relation ela untadhi ra manaki\n12/28/23, 15:26 - Naga Siva Sai Prasanth: Chebutunavu\n12/28/23, 15:26 - Naga Siva Sai Prasanth: Lekpothe bed relationship vundha 🙄?\n12/28/23, 15:26 - Jyo👀🔥....: Nedhi eh blood group\n12/28/23, 15:27 - Naga Siva Sai Prasanth: Inka\n12/28/23, 15:27 - Naga Siva Sai Prasanth: Evi vodule\n12/28/23, 15:27 - Jyo👀🔥....: Chpu raa\n12/28/23, 15:27 - Naga Siva Sai Prasanth: Diversions\n12/28/23, 15:27 - Naga Siva Sai Prasanth: Madyalo\n12/28/23, 15:27 - Naga Siva Sai Prasanth: Gb baby 👶\n12/28/23, 15:27 - Jyo👀🔥....: Nenem divert chesanu\n12/28/23, 15:27 - Naga Siva Sai Prasanth: ..\n12/28/23, 15:27 - Jyo👀🔥....: Ha....adiga...\n12/28/23, 15:27 - Jyo👀🔥....: Blood relation ledhu annav ga\n12/28/23, 15:27 - Jyo👀🔥....: Andhuke adiga\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Sarle tffr sorry bye\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Nenu emi\n12/28/23, 15:28 - Jyo👀🔥....: Nv saduvkovalaa\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Adganule. ..\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Nuv\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Lib lo vundhi\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Tffr sadvuko sollu\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Edhuku\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Mali nannu\n12/28/23, 15:28 - Jyo👀🔥....: Nen em sadavatledhlee\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Antavvu\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Sorry\n12/28/23, 15:28 - Naga Siva Sai Prasanth: For disturbance\n12/28/23, 15:28 - Naga Siva Sai Prasanth: Good bye\n12/28/23, 15:28 - Jyo👀🔥....: Oreyyy\nNen 2 gantalu lib lo unna kooda tappenaa\n12/28/23, 15:29 - Jyo👀🔥....: Nvem disturbance kadhule naku\n12/28/23, 15:29 - Naga Siva Sai Prasanth: U r wish\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Nenu\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Emi annaule inka\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Sorry\n12/28/23, 15:29 - Jyo👀🔥....: Oyee\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Akka. .\n12/28/23, 15:29 - Jyo👀🔥....: Inka ekkuva cheyku\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Good bye\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Inka mali\n12/28/23, 15:29 - Jyo👀🔥....: No\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Nenu edho okati antannu\n12/28/23, 15:29 - Naga Siva Sai Prasanth: Nenu\n12/28/23, 15:30 - Naga Siva Sai Prasanth: Chat chesi daggra nuchi\n12/28/23, 15:30 - Jyo👀🔥....: Parvaledhu\n12/28/23, 15:30 - Naga Siva Sai Prasanth: Good bye 💔🙏🙄\U0001fae0\n12/28/23, 15:30 - Jyo👀🔥....: Naku\n12/28/23, 15:30 - Jyo👀🔥....: No problem for me\n12/28/23, 15:30 - Jyo👀🔥....: 🙄🙄🙄\n12/28/23, 15:30 - Naga Siva Sai Prasanth: 👎💔💔😭\n12/28/23, 15:30 - Jyo👀🔥....: ☹️☹️☹️\n12/28/23, 15:30 - Naga Siva Sai Prasanth: 😶😶😶\n12/28/23, 15:30 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 15:30 - Jyo👀🔥....: Mothaniki....adigindanki cheppaledhu\n12/28/23, 15:30 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 15:30 - Jyo👀🔥....: Nv\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Inka naku\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Samadhamu\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Ledu\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Nuv chepaku emi\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Naku\n12/28/23, 15:31 - Jyo👀🔥....: Em sambandham ledhu\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Nenu chepanu\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Good bye\n12/28/23, 15:31 - Naga Siva Sai Prasanth: Em ledu\n12/28/23, 15:31 - Jyo👀🔥....: Cheppu\n12/28/23, 15:31 - Jyo👀🔥....: ☹️☹️\n12/28/23, 15:31 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 15:31 - Jyo👀🔥....: Prashu baabu\n12/28/23, 15:32 - Jyo👀🔥....: 😶😶😶\n12/28/23, 15:32 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 15:32 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 15:32 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 15:32 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 15:32 - Jyo👀🔥....: 🤕🤕🤕\n12/28/23, 15:32 - Naga Siva Sai Prasanth: I am died\n12/28/23, 15:32 - Jyo👀🔥....: Arey...nanaa\n12/28/23, 15:32 - Naga Siva Sai Prasanth: Good bye..\n12/28/23, 15:32 - Jyo👀🔥....: Nooo\n12/28/23, 15:32 - Naga Siva Sai Prasanth: nana\n12/28/23, 15:32 - Naga Siva Sai Prasanth: Anaku\n12/28/23, 15:32 - Naga Siva Sai Prasanth: 😡😡\n12/28/23, 15:33 - Jyo👀🔥....: Chollyyyyy\nPrashu\n12/28/23, 15:33 - Naga Siva Sai Prasanth: Inka. .\n12/28/23, 15:33 - Naga Siva Sai Prasanth: Sorry jyothirm💔i\n12/28/23, 15:33 - Jyo👀🔥....: Endhuku ra\n12/28/23, 15:34 - Jyo👀🔥....: Sare.....\nEvng vasthava...rava... edho okati cheppu\n12/28/23, 15:34 - Naga Siva Sai Prasanth: No comments\n12/28/23, 15:34 - Naga Siva Sai Prasanth: Neku naku\n12/28/23, 15:34 - Naga Siva Sai Prasanth: Sambadhamu\n12/28/23, 15:34 - Jyo👀🔥....: Just say\nYes or no\n12/28/23, 15:34 - Naga Siva Sai Prasanth: Ledu cutted\n12/28/23, 15:34 - Jyo👀🔥....: ....\n12/28/23, 15:34 - Naga Siva Sai Prasanth: No comments\n12/28/23, 15:34 - Naga Siva Sai Prasanth: Good bye\n12/28/23, 15:34 - Naga Siva Sai Prasanth: 💔💔😡\n12/28/23, 15:35 - Jyo👀🔥....: Sare....ne istam\n12/28/23, 15:35 - Jyo👀🔥....: Nene pothanle\n12/28/23, 15:35 - Naga Siva Sai Prasanth: Good 💔💔😡\n12/28/23, 15:35 - Naga Siva Sai Prasanth: Bye\n12/28/23, 15:35 - Naga Siva Sai Prasanth: Jyothirm💔i akka\n12/28/23, 15:35 - Jyo👀🔥....: 😶😶😶\n12/28/23, 16:55 - Naga Siva Sai Prasanth: Sry\n12/28/23, 16:55 - Naga Siva Sai Prasanth: For disturbing\n12/28/23, 16:55 - Naga Siva Sai Prasanth: Marchipoyi\n12/28/23, 16:56 - Naga Siva Sai Prasanth: Chesale\n12/28/23, 16:56 - Naga Siva Sai Prasanth: No calls inka\n12/28/23, 16:57 - Naga Siva Sai Prasanth: Nenu chesinapudu nuve lift cheyaku nuv chesinapudu nenu kooda lift cheyanule..\n12/28/23, 16:57 - Naga Siva Sai Prasanth: Bye baby\n12/28/23, 17:02 - Jyo👀🔥....: Endhuku baby ala antav\n12/28/23, 17:02 - Naga Siva Sai Prasanth: Anthae inka\n12/28/23, 17:02 - Naga Siva Sai Prasanth: Break up baby\n12/28/23, 17:02 - Naga Siva Sai Prasanth: 😶😶😭😭🤧\n12/28/23, 17:02 - Naga Siva Sai Prasanth: Ice cream eppichu\n12/28/23, 17:03 - Naga Siva Sai Prasanth: Vey elagoo lib lo vunavu ga fc pakkanega\n12/28/23, 17:03 - Jyo👀🔥....: Night ki vasthava mari\n12/28/23, 17:03 - Jyo👀🔥....: Fc ki\n12/28/23, 17:03 - Naga Siva Sai Prasanth: Okay. .\n12/28/23, 17:03 - Jyo👀🔥....: Okay\n12/28/23, 17:03 - Naga Siva Sai Prasanth: Break up\n12/28/23, 17:03 - Naga Siva Sai Prasanth: Aidhi ga\n12/28/23, 17:03 - Naga Siva Sai Prasanth: Na mokkamu ela chupchali\n12/28/23, 17:03 - Naga Siva Sai Prasanth: Neku...\n12/28/23, 17:03 - Jyo👀🔥....: Avvaledhu\n12/28/23, 17:04 - Jyo👀🔥....: So...no problem\n12/28/23, 17:04 - Naga Siva Sai Prasanth: Sare aithey vasthale\n12/28/23, 17:04 - Jyo👀🔥....: Okay\n12/28/23, 17:04 - Naga Siva Sai Prasanth: 🤤🤤🤤🤤\n12/28/23, 17:04 - Jyo👀🔥....: Time chepthe... vastha nenu\n12/28/23, 17:04 - Naga Siva Sai Prasanth: Chepu\n12/28/23, 17:04 - Jyo👀🔥....: Uhh\n12/28/23, 17:05 - Jyo👀🔥....: Eppudu Nene chepthaa\n12/28/23, 17:05 - Jyo👀🔥....: Ippudu nv chepthe nen vastha\n12/28/23, 17:05 - Naga Siva Sai Prasanth: U\n12/28/23, 17:05 - Naga Siva Sai Prasanth: Cheppu\n12/28/23, 17:05 - Naga Siva Sai Prasanth: Nenu cheppaka pothe ravu ga\n12/28/23, 17:06 - Naga Siva Sai Prasanth: Aithey\n12/28/23, 17:06 - Naga Siva Sai Prasanth: Chi po vey <This message was edited>\n12/28/23, 17:06 - Naga Siva Sai Prasanth: Jyo baby 🍼👶\n12/28/23, 17:18 - Jyo👀🔥....: Hloo\n12/28/23, 17:18 - Jyo👀🔥....: Prashu baabu\n12/28/23, 17:18 - Jyo👀🔥....: Nv eppudu free ante appude\n12/28/23, 17:20 - Naga Siva Sai Prasanth: Nenu\n12/28/23, 17:20 - Naga Siva Sai Prasanth: Always\n12/28/23, 17:20 - Naga Siva Sai Prasanth: Free jyo..\n12/28/23, 17:21 - Jyo👀🔥....: Abboo\n12/28/23, 17:21 - Jyo👀🔥....: Sare\n12/28/23, 17:21 - Jyo👀🔥....: 1 or 2 cheppu\n12/28/23, 17:21 - Naga Siva Sai Prasanth: 2\n12/28/23, 17:22 - Jyo👀🔥....: Aithey...7.30\n12/28/23, 17:22 - Jyo👀🔥....: Okay ga..neku\n12/28/23, 17:22 - Naga Siva Sai Prasanth: Okay..\n12/28/23, 19:18 - Jyo👀🔥....: Heloo\n12/28/23, 19:18 - Naga Siva Sai Prasanth: Ha\n12/28/23, 19:19 - Jyo👀🔥....: Em chesthunnav baabu\n12/28/23, 19:19 - Naga Siva Sai Prasanth: Phn chustuna\n12/28/23, 19:19 - Naga Siva Sai Prasanth: Paddukoni\n12/28/23, 19:20 - Jyo👀🔥....: Sarle\nNen vachesthunna\n12/28/23, 19:20 - Naga Siva Sai Prasanth: <Media omitted>\n12/28/23, 21:14 - Jyo👀🔥....: <Media omitted>\n12/28/23, 21:14 - Jyo👀🔥....: Daddy ki theskunnan ra\n12/28/23, 21:16 - Naga Siva Sai Prasanth: En\n12/28/23, 21:16 - Naga Siva Sai Prasanth: Em vacation\n12/28/23, 21:16 - Naga Siva Sai Prasanth: Mari\n12/28/23, 21:16 - Naga Siva Sai Prasanth: Naa kosamu ani sollu\n12/28/23, 21:16 - Naga Siva Sai Prasanth: Chepavu\n'

In [70]:
pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr pattern
# pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern

In [71]:
messages = re.split(pattern,data)[1:]
dates = re.findall(pattern,data)
df = pd.DataFrame({'user_message':messages, 'message_date':dates})

In [72]:
df

                                          user_message        message_date
0    Messages and calls are end-to-end encrypted. N...    9/5/23, 21:29 -
1            Naga Siva Sai Prasanth: <Media omitted>\n    9/9/23, 01:07 -
2            Naga Siva Sai Prasanth: <Media omitted>\n    9/9/23, 01:19 -
3                         Jyo👀🔥....: <Media omitted>\n    9/9/23, 22:29 -
4                         Jyo👀🔥....: <Media omitted>\n   9/12/23, 01:23 -
..                                                 ...                 ...
381                       Naga Siva Sai Prasanth: En\n  12/28/23, 21:16 -
382              Naga Siva Sai Prasanth: Em vacation\n  12/28/23, 21:16 -
383                     Naga Siva Sai Prasanth: Mari\n  12/28/23, 21:16 -
384     Naga Siva Sai Prasanth: Naa kosamu ani sollu\n  12/28/23, 21:16 -
385                  Naga Siva Sai Prasanth: Chepavu\n  12/28/23, 21:16 -

[386 rows x 2 columns]

In [74]:
df[1:]

                                       user_message        message_date
1         Naga Siva Sai Prasanth: <Media omitted>\n    9/9/23, 01:07 -
2         Naga Siva Sai Prasanth: <Media omitted>\n    9/9/23, 01:19 -
3                      Jyo👀🔥....: <Media omitted>\n    9/9/23, 22:29 -
4                      Jyo👀🔥....: <Media omitted>\n   9/12/23, 01:23 -
5                      Jyo👀🔥....: <Media omitted>\n   9/12/23, 01:57 -
..                                              ...                 ...
381                    Naga Siva Sai Prasanth: En\n  12/28/23, 21:16 -
382           Naga Siva Sai Prasanth: Em vacation\n  12/28/23, 21:16 -
383                  Naga Siva Sai Prasanth: Mari\n  12/28/23, 21:16 -
384  Naga Siva Sai Prasanth: Naa kosamu ani sollu\n  12/28/23, 21:16 -
385               Naga Siva Sai Prasanth: Chepavu\n  12/28/23, 21:16 -

[385 rows x 2 columns]

In [151]:
messages

['Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n',
 'ysrfoundation2: Hii\n',
 'Sahithi Dad: Hlo\n',
 'ysrfoundation2: Hiii\n',
 'ysrfoundation2: Sahithi\n',
 'ysrfoundation2: What are you doing\n',
 'Sahithi Dad: Ntg\n',
 'Sahithi Dad: Ra\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: null\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: null\n',
 'Sahithi Dad: Am ayna telisinda\n',
 'ysrfoundation2: Ledhu sir chuda lee anta\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Burra paadu\n',
 'Sahithi Dad: Asalu\n',
 'ysrfoundation2: Sahithi pottidi ki msg cheyu raa\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Yevariki\n',
 'Sahithi Dad: Chellu kaa\n',
 'ysrfoundation2: Mi head ki\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Na gubalu yegara gottey galadu le\n',
 'ysrfoundation2: 🤣🤣🤣\n',
 'ysrfoundation2: Sare tinnava\n',
 'Sahithi Dad: Haa\n',
 'Sahithi Dad: Nuvvo\n',
 'Sahithi Dad: Call cheyyamane vadiki\n',
 'Sahithi Dad: Vadhu\n',
 'Sahithi Dad: Le\n',
 'ysrfoundation2: Ledhu time chusava\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Ade chepthunna\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Ohh\n',
 'Sahithi Dad: Ledu ledu\n',
 'ysrfoundation2: Hoo\n',
 'ysrfoundation2: Inkante\n',
 'Sahithi Dad: Burra paadu\n',
 'Sahithi Dad: Kadupula noppi\n',
 'Sahithi Dad: Yeh visyam clarity ga telidhu\n',
 'Sahithi Dad: Chi\n',
 'Sahithi Dad: Am clg yeh babu\n',
 'Sahithi Dad: Manadu\n',
 'Sahithi Dad: Manadi\n',
 'ysrfoundation2: Haa same feeling kani chepa lenu\n',
 'Sahithi Dad: 😢\n',
 'ysrfoundation2: Sare Lee vadu reply Este niku msg chesta lee\n',
 'Sahithi Dad: Kk\n',
 'Sahithi Dad: Padmavathi clg kuda selavu\n',
 'ysrfoundation2: Hoo appude adige sava\n',
 'Sahithi Dad: Fast nenu\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Selavu manaki kuda\n',
 'Sahithi Dad: Tomorrow (05.12.23) college holiday\n',
 'ysrfoundation2: S\n',
 'ysrfoundation2: Super\n',
 'Sahithi Dad: Am antha badha\n',
 'ysrfoundation2: Arey maa Chelli pettamandi petta\n',
 'ysrfoundation2: Niku badha ante CLG tmrw holiday estaro ledho ani\n',
 'Sahithi Dad: Nakaa\n',
 'ysrfoundation2: Ledhu naku ani pettali kani mistake\n',
 'Sahithi Dad: Ohh\n',
 'Sahithi Dad: Me chelli ki echara\n',
 'Sahithi Dad: Selavu\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Hi\n',
 'Sahithi Dad: Chadivesava\n',
 'ysrfoundation2: Ledhu\n',
 'ysrfoundation2: Tmrw holiday estaro amo ani balance uncha\n',
 'Sahithi Dad: Evvaru mari\n',
 'ysrfoundation2: Hoo sare evvaku pothe ledhu\n',
 'ysrfoundation2: Ante\n',
 'Sahithi Dad: Jyothi akka vallu bojanam ki pilichara meku\n',
 'ysrfoundation2: Epudu\n',
 'Sahithi Dad: Repu\n',
 'ysrfoundation2: Emo naku telidhu\n',
 'Sahithi Dad: Me mummy ki adigi cheppu\n',
 'ysrfoundation2: Sare kani\n',
 'ysrfoundation2: Nuvvu chadesava\n',
 'Sahithi Dad: Ledu ra\n',
 'Sahithi Dad: Bayam vesthundi\n',
 'Sahithi Dad: Naku\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Haaa\n',
 'Sahithi Dad: Send me\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Today\n',
 'Sahithi Dad: Holiday\n',
 'Sahithi Dad: Msg chudu grouplo\n',
 'ysrfoundation2: Hoo super raa\n',
 'Sahithi Dad: Orey\n',
 'Sahithi Dad: Bojanalaki vasthava\n',
 'Sahithi Dad: Shake\n',
 'ysrfoundation2: Hiii\n',
 'ysrfoundation2: Tinnava\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: Hlo\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: 💯\n',
 'ysrfoundation2: 😍😍\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Nice\n',
 'ysrfoundation2: 😚😚\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Shop now on Meesho! \nhttps://www.meesho.com/s/p/4w7qta?utm_source=s_w\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: https://youtu.be/nZqD1FyXdBE?si=LgG8tjA9U4orjAjz\n',
 'ysrfoundation2: Arey EDI oka sari chudu\n',
 'Sahithi Dad: Ila vuntundi aa\n',
 'ysrfoundation2: Haa\n',
 'ysrfoundation2: Epudu Mari pondi\n',
 'Sahithi Dad: Enti\n',
 'Sahithi Dad: Pondi enti ra\n',
 'ysrfoundation2: Epudu Mari poindhi  raa\n',
 'Sahithi Dad: Baledu antunnava\n',
 'Sahithi Dad: Ma intlo chala long antunnaru\n',
 'ysrfoundation2: Ledhu raa super ga chesaru antunna\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Avunu\n',
 'ysrfoundation2: Emo time undi kadha chudam\n',
 'Sahithi Dad: Haa sare le\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Arey balloons ne phone lo order cheyu raa\n',
 'ysrfoundation2: Epudu cheste aapudo vastadi\n',
 'Sahithi Dad: Na phone lo nenu yeppudu pettaledu ra\n',
 'Sahithi Dad: Ne phone lo petti money kavalante echestha\n',
 'Sahithi Dad: Aishu ma nanna money adigaru ra\n',
 'ysrfoundation2: Arey 350 ani chepamannadi taruvata chudam annadu\n',
 'ysrfoundation2: Ok na\n',
 'Sahithi Dad: Yevaru\n',
 'ysrfoundation2: Ma mom\n',
 'Sahithi Dad: Adi kaadu yeh babu\n',
 'ysrfoundation2: Mari enti\n',
 'Sahithi Dad: Cheppuluvi, kit vi\n',
 'ysrfoundation2: Enti ardham kaledhu\n',
 'ysrfoundation2: Phone cheyyala\n',
 'Sahithi Dad: Cheppulu\n',
 'Sahithi Dad: Baby kit usha valla babu ki teesukunnam kada\n',
 'Sahithi Dad: Aa money\n',
 'ysrfoundation2: Haa sare\n',
 'Sahithi Dad: Nenu raanu ra\n',
 'ysrfoundation2: Em\n',
 'Sahithi Dad: Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Haaa\n',
 'ysrfoundation2: Sare kani money anta\n',
 'Sahithi Dad: 280 ra\n',
 'Sahithi Dad: Monna 50 icha annav kada\n',
 'Sahithi Dad: 230\n',
 'ysrfoundation2: Haa kk\n',
 'Sahithi Dad: Haa sare\n',
 'Sahithi Dad: 🙏🏻\n',
 'Sahithi Dad: Y\n',
 'ysrfoundation2: Song baledha\n',
 'Sahithi Dad: Super\n',
 'ysrfoundation2: Anduke petta reasons em ledhu\n',
 'Sahithi Dad: Aishu pettava photo\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Enti ra\n',
 'ysrfoundation2: Hii sahithi\n',
 'Sahithi Dad: Hi ra\n',
 'Sahithi Dad: Photo pettava\n',
 'ysrfoundation2: Haa pedata lee\n',
 'Sahithi Dad: Sry raledu endhuku ante dress change cheyledu\n',
 'Sahithi Dad: Andhuke\n',
 'ysrfoundation2: Paravaledu lee\n',
 'ysrfoundation2: Akhila kavi vacharu\n',
 'Sahithi Dad: Marchipoku e roju pettu\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Videos pettu\n',
 'Sahithi Dad: Naku\n',
 'Sahithi Dad: Puja vi\n',
 'ysrfoundation2: Haa\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Aishu pettava\n',
 'Sahithi Dad: Photo\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Am annaru\n',
 'Sahithi Dad: Oley hd vi pettamani cheppa kadey\n',
 'Sahithi Dad: 🫢\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hii\n',
 'Sahithi Dad: Chadivesava madam\n',
 'ysrfoundation2: Ledhu raa maths main chudali\n',
 'Sahithi Dad: Chusava mari\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: You deleted this message\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Chadivesava\n',
 'ysrfoundation2: Ledhu\n',
 'Sahithi Dad: Nv brilliant le appudu kappudu ayna chusi rasesthav\n',
 'ysrfoundation2: Haa avunu lee\n',
 'Sahithi Dad: Yes its true\n',
 'Sahithi Dad: Aishu e question chadivava\n',
 'ysrfoundation2: Nanu asalu em chadavale\n',
 'Sahithi Dad: Avunaa\n',
 'Sahithi Dad: Sare le\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Send me\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Adigava\n',
 'Sahithi Dad: Vallaki  am annaru\n',
 'ysrfoundation2: Avariki\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Anu monika mani vallaki\n',
 'ysrfoundation2: Haa kk moni , rama\n',
 'ysrfoundation2: Anu kudha m avvaka pote  annadi\n',
 'ysrfoundation2: Hii\n',
 'Sahithi Dad: Hii\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: Am doing\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa\n',
 'Sahithi Dad: Rama raadhu aa\n',
 'ysrfoundation2: Ante mrng varuku telidhu\n',
 'Sahithi Dad: Am alaga\n',
 'ysrfoundation2: Emo\n',
 'Sahithi Dad: Avuna\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Inko 4members yevaru ra\n',
 'ysrfoundation2: Chinnamudu , paiga vallu avaro anta family nee\n',
 'Sahithi Dad: Ohh kk le\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali\n',
 'Sahithi Dad: Sare\n',
 'ysrfoundation2: Sare inka\n',
 'Sahithi Dad: Cheppali\n',
 'ysrfoundation2: Ante tmrw kosam adaina cheppu\n',
 'Sahithi Dad: Games aa\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Okka 5min aaagu\n',
 'Sahithi Dad: Msg chesthanu\n',
 'ysrfoundation2: Kk\n',
 'Sahithi Dad: Yeh dress vesthav\n',
 'ysrfoundation2: Nenu birthday di anukuntunna u\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Mari nenu am veyyali\n',
 'Sahithi Dad: Authe\n',
 'ysrfoundation2: Emo nuvve Alo chinchu\n',
 'Sahithi Dad: Cheppu nuvvu\n',
 'ysrfoundation2: Naku ala telustunndi\n',
 'Sahithi Dad: Na dresslu anni chusav kada\n',
 'ysrfoundation2: Emo raa nuvve decide avvu\n',
 'Sahithi Dad: Sare le\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Edi ok naa\n',
 'ysrfoundation2: Haa kk\n',
 'Sahithi Dad: Kk le\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Leka pothe inko top vundi\n',
 'ysrfoundation2: Ado\n',
 'Sahithi Dad: Kothadi adi ayna vadesthanu le\n',
 'ysrfoundation2: Haa ne estam nee dress\n',
 'Sahithi Dad: Sare le\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Inkem games adugu mani vallaki\n',
 'ysrfoundation2: Hiii sahi\n',
 'ysrfoundation2: Anu ki phone cheyu oka sari adugu\n',
 'Sahithi Dad: Sare\n',
 'Sahithi Dad: Hi\n',
 'Sahithi Dad: Enni gantalaki ra\n',
 'Sahithi Dad: Aishu phone pay number pettu money phone pay chestha\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: 9949437849\n',
 'ysrfoundation2: Kk naa\n',
 'Sahithi Dad: Kk\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Orey phone pay maadi avvatledu limit aypoyindi madi e roju di\n',
 'Sahithi Dad: Mrng thechi echesthanu me daddy ki cheppu\n',
 'ysrfoundation2: Kk\n',
 'Sahithi Dad: Evena pics mari levaa\n',
 'ysrfoundation2: Haa rassu ki cheppa\n',
 'ysrfoundation2: Tana daggara konni vunnay\n',
 'ysrfoundation2: Oka sari nuvvu msg pettu\n',
 'Sahithi Dad: Kk\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: https://www.instagram.com/reel/C1J_HW6pjTb/?igsh=N2ZiNzVhMjY2OA==\n',
 'ysrfoundation2: 🤣🤣\n',
 'Sahithi Dad: 😂\n',
 'Sahithi Dad: Date chusava\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Sahithi nee English key nadaggara vundi\n',
 'Sahithi Dad: Ade vethika\n',
 'Sahithi Dad: Chala sepu\n',
 'ysrfoundation2: Hoo nenu epudo msg petta\n',
 'Sahithi Dad: Mobile vundadu ani telusu gaa neku\n',
 'Sahithi Dad: 12th answer pettava\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Tqqq❤️😘🥰\n',
 'ysrfoundation2: Abho chalu lee\n',
 'Sahithi Dad: 😄\n',
 'Sahithi Dad: Open chesava\n',
 'Sahithi Dad: Set\n',
 'ysrfoundation2: Haa chusa\n',
 'ysrfoundation2: Pump evvale ante\n',
 'ysrfoundation2: Anni kk\n',
 'Sahithi Dad: Evvaleda pump\n',
 'ysrfoundation2: Ledhu\n',
 'Sahithi Dad: Kkk\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: https://youtube.com/shorts/Ze8DjY_4kVQ?si=CXBIMqJh3p7cPOzm\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Photo pettu\n',
 'ysrfoundation2: Aa photo\n',
 'Sahithi Dad: Frame\n',
 'ysrfoundation2: Pack chesadhu vadu\n',
 'Sahithi Dad: Avuna\n',
 'Sahithi Dad: Nv kuda chudaledha\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Ledhu\n',
 'Sahithi Dad: Indhaka yekkadiki vellav\n',
 'Sahithi Dad: Gift kosam aa\n',
 'ysrfoundation2: Sorry wrong answer pakodi kosam\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Gift konta annav\n',
 'ysrfoundation2: Haa tmrw suprise miku ,anu ki kudha\n',
 'Sahithi Dad: Nku cheppu le\n',
 'Sahithi Dad: Parledu\n',
 'ysrfoundation2: Tmrw chustav kadha\n',
 'Sahithi Dad: Cheppu\n',
 'Sahithi Dad: Ra\n',
 'ysrfoundation2: Bye muggulu chustunna\n',
 'Sahithi Dad: Cheppava\n',
 'Sahithi Dad: Anthe n\n',
 'Sahithi Dad: Nenu neku telisinatte chesa ga yedi chesinaa\n',
 'Sahithi Dad: Edi cheating asalu\n',
 'ysrfoundation2: Ledhu raa inka em konalo decide avvale anduke\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Aishu chude yelaga chesado\n',
 'Sahithi Dad: Chala kopam ga vundi vaadi medha\n',
 'ysrfoundation2: Haa delete kudha cheya lee\n',
 'Sahithi Dad: Cheyyadu vaadu nku telusu\n',
 'ysrfoundation2: Haa Mari em chestam nenu , nuvvu kudha chudale\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Arey cake kosam money enta\n',
 'ysrfoundation2: Cheppa lee\n',
 'ysrfoundation2: Sare anu status chusava\n',
 'Sahithi Dad: Me estham yeh\n',
 'Sahithi Dad: Vaadu inka delete cheyleda\n',
 'Sahithi Dad: Naku chala chiraku ga vundi\n',
 'Sahithi Dad: Anu kuda status pettisindi\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Vinu\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: Tmrw chemistry bullet evvu\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: https://www.instagram.com/reel/C1i2zXhp-En/?igsh=MWp4bDQ1MmhxemtyOQ==\n',
 'Sahithi Dad: <Media omitted>\n',
 'ysrfoundation2: Arey msg cheyu tanuja ki\n',
 'ysrfoundation2: Plss\n',
 'Sahithi Dad: Kk\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Arey manam Ela nee epudaina photos tesukundam kk naa\n',
 'Sahithi Dad: Done done 👍👍👍\n',
 'ysrfoundation2: Sare chemistry photos pettu\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Ammo chadivedham ane\n',
 'ysrfoundation2: Haa kani epudu di ee paper\n',
 'Sahithi Dad: Repatiki\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Hiiii\n',
 'Sahithi Dad: Hi\n',
 'Sahithi Dad: Ame\n',
 'ysrfoundation2: Arey EDI accident naku estam raa ee movie lo\n',
 'ysrfoundation2: https://youtube.com/shorts/GM1tIe2jD-c?si=M_ehiKgESYV0vU7F\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Naa kallu Edo chepuko\n']

In [152]:
df

                                          user_message            message_date
0    Messages and calls are end-to-end encrypted. N...  30/11/2023, 7:44 am -
1                                ysrfoundation2: Hii\n  30/11/2023, 7:45 am -
2                                   Sahithi Dad: Hlo\n  30/11/2023, 7:49 am -
3                               ysrfoundation2: Hiii\n  03/12/2023, 1:34 pm -
4                            ysrfoundation2: Sahithi\n  03/12/2023, 1:52 pm -
..                                                 ...                     ...
455                                 Sahithi Dad: Ame\n  07/01/2024, 8:42 pm -
456  ysrfoundation2: Arey EDI accident naku estam r...  07/01/2024, 9:07 pm -
457  ysrfoundation2: https://youtube.com/shorts/GM1...  10/01/2024, 6:14 pm -
458                  ysrfoundation2: <Media omitted>\n  10/01/2024, 6:54 pm -
459            ysrfoundation2: Naa kallu Edo chepuko\n  10/01/2024, 6:55 pm -

[460 rows x 2 columns]

In [153]:
    users = []
    messages = []

In [154]:
for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1: ]:
            users.append(entry[1])
            messages.append(entry[2])

In [155]:
users

['ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2']

In [156]:

messages

['Hii\n',
 'Hlo\n',
 'Hiii\n',
 'Sahithi\n',
 'What are you doing\n',
 'Ntg\n',
 'Ra\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'null\n',
 'null\n',
 'null\n',
 'Am ayna telisinda\n',
 'Ledhu sir chuda lee anta\n',
 'Avunaa\n',
 'Hmm\n',
 'Burra paadu\n',
 'Asalu\n',
 'Sahithi pottidi ki msg cheyu raa\n',
 'Haa\n',
 'Yevariki\n',
 'Chellu kaa\n',
 'Mi head ki\n',
 'Haa\n',
 'Na gubalu yegara gottey galadu le\n',
 '🤣🤣🤣\n',
 'Sare tinnava\n',
 'Haa\n',
 'Nuvvo\n',
 'Call cheyyamane vadiki\n',
 'Vadhu\n',
 'Le\n',
 'Ledhu time chusava\n',
 'Hoo\n',
 'Ade chepthunna\n',
 'Hmm\n',
 'Ohh\n',
 'Ledu ledu\n',
 'Hoo\n',
 'Inkante\n',
 'Burra paadu\n',
 'Kadupula noppi\n',
 'Yeh visyam clarity ga telidhu\n',
 'Chi\n',
 'Am clg yeh babu\n',
 'Manadu\n',
 'Manadi\n',
 'Haa same feeling kani chepa lenu\n',
 '😢\n',
 'Sare Lee vadu reply Este niku msg chesta lee\n',
 'Kk\n',
 'Padmavathi clg kuda selavu\n',
 'Hoo appude adige sava\n',
 'Fast nenu\n',
 '<Media omitted>\n',
 'Selavu manaki kuda\n',
 'Tomorrow (05.12.23) college holiday\n',
 'S\n',
 'Super\n',
 'Am antha badha\n',
 'Arey maa Chelli pettamandi petta\n',
 'Niku badha ante CLG tmrw holiday estaro ledho ani\n',
 'Nakaa\n',
 'Ledhu naku ani pettali kani mistake\n',
 'Ohh\n',
 'Me chelli ki echara\n',
 'Selavu\n',
 'Haa\n',
 'Hi\n',
 'Chadivesava\n',
 'Ledhu\n',
 'Tmrw holiday estaro amo ani balance uncha\n',
 'Evvaru mari\n',
 'Hoo sare evvaku pothe ledhu\n',
 'Ante\n',
 'Jyothi akka vallu bojanam ki pilichara meku\n',
 'Epudu\n',
 'Repu\n',
 'Emo naku telidhu\n',
 'Me mummy ki adigi cheppu\n',
 'Sare kani\n',
 'Nuvvu chadesava\n',
 'Ledu ra\n',
 'Bayam vesthundi\n',
 'Naku\n',
 'Hoo\n',
 'Haaa\n',
 'Send me\n',
 '<Media omitted>\n',
 'Today\n',
 'Holiday\n',
 'Msg chudu grouplo\n',
 'Hoo super raa\n',
 'Orey\n',
 'Bojanalaki vasthava\n',
 'Shake\n',
 'Hiii\n',
 'Tinnava\n',
 'Hi\n',
 'Hiii\n',
 'Hlo\n',
 'Aishu\n',
 '💯\n',
 '😍😍\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Nice\n',
 '😚😚\n',
 '<Media omitted>\n',
 'Shop now on Meesho! \nhttps://www.meesho.com/s/p/4w7qta?utm_source=s_w\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'https://youtu.be/nZqD1FyXdBE?si=LgG8tjA9U4orjAjz\n',
 'Arey EDI oka sari chudu\n',
 'Ila vuntundi aa\n',
 'Haa\n',
 'Epudu Mari pondi\n',
 'Enti\n',
 'Pondi enti ra\n',
 'Epudu Mari poindhi  raa\n',
 'Baledu antunnava\n',
 'Ma intlo chala long antunnaru\n',
 'Ledhu raa super ga chesaru antunna\n',
 'Hoo\n',
 'Avunu\n',
 'Emo time undi kadha chudam\n',
 'Haa sare le\n',
 'Hmm\n',
 'Arey balloons ne phone lo order cheyu raa\n',
 'Epudu cheste aapudo vastadi\n',
 'Na phone lo nenu yeppudu pettaledu ra\n',
 'Ne phone lo petti money kavalante echestha\n',
 'Aishu ma nanna money adigaru ra\n',
 'Arey 350 ani chepamannadi taruvata chudam annadu\n',
 'Ok na\n',
 'Yevaru\n',
 'Ma mom\n',
 'Adi kaadu yeh babu\n',
 'Mari enti\n',
 'Cheppuluvi, kit vi\n',
 'Enti ardham kaledhu\n',
 'Phone cheyyala\n',
 'Cheppulu\n',
 'Baby kit usha valla babu ki teesukunnam kada\n',
 'Aa money\n',
 'Haa sare\n',
 'Nenu raanu ra\n',
 'Em\n',
 'Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru\n',
 'Hoo\n',
 'Haaa\n',
 'Sare kani money anta\n',
 '280 ra\n',
 'Monna 50 icha annav kada\n',
 '230\n',
 'Haa kk\n',
 'Haa sare\n',
 '🙏🏻\n',
 'Y\n',
 'Song baledha\n',
 'Super\n',
 'Anduke petta reasons em ledhu\n',
 'Aishu pettava photo\n',
 '<Media omitted>\n',
 'Enti ra\n',
 'Hii sahithi\n',
 'Hi ra\n',
 'Photo pettava\n',
 'Haa pedata lee\n',
 'Sry raledu endhuku ante dress change cheyledu\n',
 'Andhuke\n',
 'Paravaledu lee\n',
 'Akhila kavi vacharu\n',
 'Marchipoku e roju pettu\n',
 'Avunaa\n',
 'Haa\n',
 'Videos pettu\n',
 'Naku\n',
 'Puja vi\n',
 'Haa\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Aishu pettava\n',
 'Photo\n',
 'Haa\n',
 'Am annaru\n',
 'Oley hd vi pettamani cheppa kadey\n',
 '🫢\n',
 'Hi\n',
 'Hii\n',
 'Chadivesava madam\n',
 'Ledhu raa maths main chudali\n',
 'Chusava mari\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'You deleted this message\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Chadivesava\n',
 'Ledhu\n',
 'Nv brilliant le appudu kappudu ayna chusi rasesthav\n',
 'Haa avunu lee\n',
 'Yes its true\n',
 'Aishu e question chadivava\n',
 'Nanu asalu em chadavale\n',
 'Avunaa\n',
 'Sare le\n',
 'Hmm\n',
 'Send me\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Aishu\n',
 'Adigava\n',
 'Vallaki  am annaru\n',
 'Avariki\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Anu monika mani vallaki\n',
 'Haa kk moni , rama\n',
 'Anu kudha m avvaka pote  annadi\n',
 'Hii\n',
 'Hii\n',
 'Hi\n',
 'Hiii\n',
 'Am doing\n',
 'Hiii\n',
 'Hi\n',
 'Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa\n',
 'Rama raadhu aa\n',
 'Ante mrng varuku telidhu\n',
 'Am alaga\n',
 'Emo\n',
 'Avuna\n',
 'Hmm\n',
 'Inko 4members yevaru ra\n',
 'Chinnamudu , paiga vallu avaro anta family nee\n',
 'Ohh kk le\n',
 'Hmm\n',
 'Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali\n',
 'Sare\n',
 'Sare inka\n',
 'Cheppali\n',
 'Ante tmrw kosam adaina cheppu\n',
 'Games aa\n',
 'Haa\n',
 'Okka 5min aaagu\n',
 'Msg chesthanu\n',
 'Kk\n',
 'Yeh dress vesthav\n',
 'Nenu birthday di anukuntunna u\n',
 'Avunaa\n',
 'Hmm\n',
 'Mari nenu am veyyali\n',
 'Authe\n',
 'Emo nuvve Alo chinchu\n',
 'Cheppu nuvvu\n',
 'Naku ala telustunndi\n',
 'Na dresslu anni chusav kada\n',
 'Emo raa nuvve decide avvu\n',
 'Sare le\n',
 '<Media omitted>\n',
 'Edi ok naa\n',
 'Haa kk\n',
 'Kk le\n',
 'Hmm\n',
 'Leka pothe inko top vundi\n',
 'Ado\n',
 'Kothadi adi ayna vadesthanu le\n',
 'Haa ne estam nee dress\n',
 'Sare le\n',
 'Hmm\n',
 'Inkem games adugu mani vallaki\n',
 'Hiii sahi\n',
 'Anu ki phone cheyu oka sari adugu\n',
 'Sare\n',
 'Hi\n',
 'Enni gantalaki ra\n',
 'Aishu phone pay number pettu money phone pay chestha\n',
 'null\n',
 '9949437849\n',
 'Kk naa\n',
 'Kk\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Orey phone pay maadi avvatledu limit aypoyindi madi e roju di\n',
 'Mrng thechi echesthanu me daddy ki cheppu\n',
 'Kk\n',
 'Evena pics mari levaa\n',
 'Haa rassu ki cheppa\n',
 'Tana daggara konni vunnay\n',
 'Oka sari nuvvu msg pettu\n',
 'Kk\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Hi\n',
 'Hiii\n',
 'https://www.instagram.com/reel/C1J_HW6pjTb/?igsh=N2ZiNzVhMjY2OA==\n',
 '🤣🤣\n',
 '😂\n',
 'Date chusava\n',
 '<Media omitted>\n',
 'Sahithi nee English key nadaggara vundi\n',
 'Ade vethika\n',
 'Chala sepu\n',
 'Hoo nenu epudo msg petta\n',
 'Mobile vundadu ani telusu gaa neku\n',
 '12th answer pettava\n',
 'null\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Tqqq❤️😘🥰\n',
 'Abho chalu lee\n',
 '😄\n',
 'Open chesava\n',
 'Set\n',
 'Haa chusa\n',
 'Pump evvale ante\n',
 'Anni kk\n',
 'Evvaleda pump\n',
 'Ledhu\n',
 'Kkk\n',
 '<Media omitted>\n',
 'https://youtube.com/shorts/Ze8DjY_4kVQ?si=CXBIMqJh3p7cPOzm\n',
 'Aishu\n',
 'Aishu\n',
 'Photo pettu\n',
 'Aa photo\n',
 'Frame\n',
 'Pack chesadhu vadu\n',
 'Avuna\n',
 'Nv kuda chudaledha\n',
 'Hmm\n',
 'Ledhu\n',
 'Indhaka yekkadiki vellav\n',
 'Gift kosam aa\n',
 'Sorry wrong answer pakodi kosam\n',
 'Avunaa\n',
 'Hmm\n',
 'Gift konta annav\n',
 'Haa tmrw suprise miku ,anu ki kudha\n',
 'Nku cheppu le\n',
 'Parledu\n',
 'Tmrw chustav kadha\n',
 'Cheppu\n',
 'Ra\n',
 'Bye muggulu chustunna\n',
 'Cheppava\n',
 'Anthe n\n',
 'Nenu neku telisinatte chesa ga yedi chesinaa\n',
 'Edi cheating asalu\n',
 'Ledhu raa inka em konalo decide avvale anduke\n',
 'Avunaa\n',
 'Hmm\n',
 'Aishu\n',
 'Aishu chude yelaga chesado\n',
 'Chala kopam ga vundi vaadi medha\n',
 'Haa delete kudha cheya lee\n',
 'Cheyyadu vaadu nku telusu\n',
 'Haa Mari em chestam nenu , nuvvu kudha chudale\n',
 'Hmm\n',
 'Arey cake kosam money enta\n',
 'Cheppa lee\n',
 'Sare anu status chusava\n',
 'Me estham yeh\n',
 'Vaadu inka delete cheyleda\n',
 'Naku chala chiraku ga vundi\n',
 'Anu kuda status pettisindi\n',
 '<Media omitted>\n',
 'Vinu\n',
 'Aishu\n',
 'null\n',
 'Tmrw chemistry bullet evvu\n',
 'null\n',
 '<Media omitted>\n',
 'https://www.instagram.com/reel/C1i2zXhp-En/?igsh=MWp4bDQ1MmhxemtyOQ==\n',
 '<Media omitted>\n',
 'Arey msg cheyu tanuja ki\n',
 'Plss\n',
 'Kk\n',
 '<Media omitted>\n',
 'Arey manam Ela nee epudaina photos tesukundam kk naa\n',
 'Done done 👍👍👍\n',
 'Sare chemistry photos pettu\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Ammo chadivedham ane\n',
 'Haa kani epudu di ee paper\n',
 'Repatiki\n',
 '<Media omitted>\n',
 'Hiiii\n',
 'Hi\n',
 'Ame\n',
 'Arey EDI accident naku estam raa ee movie lo\n',
 'https://youtube.com/shorts/GM1tIe2jD-c?si=M_ehiKgESYV0vU7F\n',
 '<Media omitted>\n',
 'Naa kallu Edo chepuko\n']

In [157]:
len(users)

459

In [158]:
len(messages)

459

In [159]:
len(df)

460

In [160]:
df

                                          user_message            message_date
0    Messages and calls are end-to-end encrypted. N...  30/11/2023, 7:44 am -
1                                ysrfoundation2: Hii\n  30/11/2023, 7:45 am -
2                                   Sahithi Dad: Hlo\n  30/11/2023, 7:49 am -
3                               ysrfoundation2: Hiii\n  03/12/2023, 1:34 pm -
4                            ysrfoundation2: Sahithi\n  03/12/2023, 1:52 pm -
..                                                 ...                     ...
455                                 Sahithi Dad: Ame\n  07/01/2024, 8:42 pm -
456  ysrfoundation2: Arey EDI accident naku estam r...  07/01/2024, 9:07 pm -
457  ysrfoundation2: https://youtube.com/shorts/GM1...  10/01/2024, 6:14 pm -
458                  ysrfoundation2: <Media omitted>\n  10/01/2024, 6:54 pm -
459            ysrfoundation2: Naa kallu Edo chepuko\n  10/01/2024, 6:55 pm -

[460 rows x 2 columns]

In [161]:
df = df.drop(0)

In [162]:
df = df.reset_index(drop=True)

In [163]:
df.head()

                           user_message            message_date
0                 ysrfoundation2: Hii\n  30/11/2023, 7:45 am -
1                    Sahithi Dad: Hlo\n  30/11/2023, 7:49 am -
2                ysrfoundation2: Hiii\n  03/12/2023, 1:34 pm -
3             ysrfoundation2: Sahithi\n  03/12/2023, 1:52 pm -
4  ysrfoundation2: What are you doing\n  03/12/2023, 1:52 pm -

In [164]:
len(users)

459

In [165]:
df['users'] = users 
df['messages'] = messages

In [75]:
df.head()

,user_message,message_date,users,messages
0,ysrfoundation2: Hii\n,"30/11/2023, 7:45 am -",ysrfoundation2,Hii\n
1,Sahithi Dad: Hlo\n,"30/11/2023, 7:49 am -",Sahithi Dad,Hlo\n
2,ysrfoundation2: Hiii\n,"03/12/2023, 1:34 pm -",ysrfoundation2,Hiii\n
3,ysrfoundation2: Sahithi\n,"03/12/2023, 1:52 pm -",ysrfoundation2,Sahithi\n
4,ysrfoundation2: What are you doing\n,"03/12/2023, 1:52 pm -",ysrfoundation2,What are you doing\n

In [76]:
df  = df.drop('user_message',axis=1)

In [77]:
df.head()

             message_date           users              messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii\n
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo\n
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii\n
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi\n
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing\n

In [82]:
df1 = df.copy()

In [166]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [167]:
df1 = df1[df1['messages']!='<Media omitted>\n']

In [168]:
df1 = df1[df1['messages']!='null\n']

In [169]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [170]:
len(df1)

352

In [180]:
for i in range(len(df1)):
    if('<This Message Was Edited>' in df1.loc[i]['messages']):
        df1.loc[i]['messages'] = df1.loc[i]['messages'].replace('<This Message Was Edited>','')
    if('\n' in df1.loc[i]['messages']):
        df1.loc[i]['messages'] = df1.loc[i]['messages'].replace('\n','')
    if('http' in df1.loc[i]['messages']):
        df1.drop(i,inplace=True)

In [181]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [182]:
df1 = df1.reset_index(drop=True)

In [183]:
df1

,message_date,users,messages
0,"30/11/2023, 7:45 am -",ysrfoundation2,Hii
1,"30/11/2023, 7:49 am -",Sahithi Dad,Hlo
2,"03/12/2023, 1:34 pm -",ysrfoundation2,Hiii
3,"03/12/2023, 1:52 pm -",ysrfoundation2,Sahithi
4,"03/12/2023, 1:52 pm -",ysrfoundation2,What are you doing
...,...,...,...
341,"06/01/2024, 8:58 pm -",Sahithi Dad,Hiiii
342,"07/01/2024, 8:40 pm -",Sahithi Dad,Hi
343,"07/01/2024, 8:42 pm -",Sahithi Dad,Ame
344,"07/01/2024, 9:07 pm -",ysrfoundation2,Arey EDI accident naku estam raa ee movie lo
345,"10/01/2024, 6:55 pm -",ysrfoundation2,Naa kallu Edo chepuko

In [184]:
df1.loc[0]['messages']

'Hii'

In [185]:
for i in range(len(df1)):
    df1.loc[i]['messages']  = df1.loc[i]['messages'].replace('\n', '')

In [186]:
df1

,message_date,users,messages
0,"30/11/2023, 7:45 am -",ysrfoundation2,Hii
1,"30/11/2023, 7:49 am -",Sahithi Dad,Hlo
2,"03/12/2023, 1:34 pm -",ysrfoundation2,Hiii
3,"03/12/2023, 1:52 pm -",ysrfoundation2,Sahithi
4,"03/12/2023, 1:52 pm -",ysrfoundation2,What are you doing
...,...,...,...
341,"06/01/2024, 8:58 pm -",Sahithi Dad,Hiiii
342,"07/01/2024, 8:40 pm -",Sahithi Dad,Hi
343,"07/01/2024, 8:42 pm -",Sahithi Dad,Ame
344,"07/01/2024, 9:07 pm -",ysrfoundation2,Arey EDI accident naku estam raa ee movie lo
345,"10/01/2024, 6:55 pm -",ysrfoundation2,Naa kallu Edo chepuko

In [187]:
df2 = df1.copy()

In [188]:
person1 = df2.users.unique()[0]
person2 = df2.users.unique()[1]

In [189]:
person1

'ysrfoundation2'

In [190]:
person2

'Sahithi Dad'

In [191]:
for i in range(len(df2)):
    if df2.loc[i]['users'] == person1:
        df2.loc[i]['users'] = 'A'
    elif df2.loc[i]['users'] == person2:
        df2.loc[i]['users'] = 'B'

In [196]:
for i in range(len(df1)):
    if df1.loc[i]['users'] == person1:
        df1.loc[i]['users'] = 'A'
    elif df1.loc[i]['users'] == person2:
        df1.loc[i]['users'] = 'B'

In [192]:
df2.head()

             message_date users            messages
0  30/11/2023, 7:45 am -      A                 Hii
1  30/11/2023, 7:49 am -      B                 Hlo
2  03/12/2023, 1:34 pm -      A                Hiii
3  03/12/2023, 1:52 pm -      A             Sahithi
4  03/12/2023, 1:52 pm -      A  What are you doing

In [193]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [43]:
df2.to_csv('pra_1.csv')

In [44]:
df2.head()

         message_date users                        messages
0  12/27/23, 21:36 -      A                              Ok
1  12/27/23, 21:36 -      B                  Nedhi aipoyaka
2  12/27/23, 21:36 -      B  Naku cheppu maths..4th chapter
3  12/27/23, 21:37 -      B  Okay na...Marchipoku raa nanaa
4  12/28/23, 00:03 -      B                           Hello

In [48]:
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M")
tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")

In [61]:
save_directory = "/home/user/Documents/ML_DL_PROJECTS/WhatsAppChatAnalysisProject/artifacts"
model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)

NameError: name 'model' is not defined

In [19]:
xlit_engine = Nonex
def initialize_xlit_engine(language_code="te", beam_width=10):
    global xlit_engine
    if xlit_engine is None:
        xlit_engine = XlitEngine(language_code, beam_width=beam_width)

In [55]:
def transliterator(df):
    global xlit_engine
    initialize_xlit_engine()
    outputs = []
    for i in range(len(df)): 
        output = xlit_engine.translit_sentence(df.loc[i]['messages'])
        outputs.append(output['te'])
    df['translit_msgs'] = outputs
    return df

In [2]:
df3 = pd.read_csv('pra_1.csv',index_col=None)

In [3]:
df3.head()

   Unnamed: 0        message_date users                        messages
0           0  12/27/23, 21:36 -      A                              Ok
1           1  12/27/23, 21:36 -      B                  Nedhi aipoyaka
2           2  12/27/23, 21:36 -      B  Naku cheppu maths..4th chapter
3           3  12/27/23, 21:37 -      B  Okay na...Marchipoku raa nanaa
4           4  12/28/23, 00:03 -      B                           Hello

In [4]:
df3.drop('Unnamed: 0',axis=1,inplace=True)

In [56]:
df4 = df3.copy()

In [57]:
df4 = transliterator(df4)

In [58]:
df4

,message_date,users,messages,tranlit_msg
0,"12/27/23, 21:36 -",A,Ok,ఒక్
1,"12/27/23, 21:36 -",B,Nedhi aipoyaka,నేది అయిపోయాక
2,"12/27/23, 21:36 -",B,Naku cheppu maths..4th chapter,నాకు చెప్పు మాత్స్..౪త్ చాప్టర్
3,"12/27/23, 21:37 -",B,Okay na...Marchipoku raa nanaa,ఒకే నా...మర్చిపోకు రా ననా
4,"12/28/23, 00:03 -",B,Hello,హెల్లో
...,...,...,...,...
255,"12/28/23, 21:16 -",A,En,ఎన్
256,"12/28/23, 21:16 -",A,Em vacation,ఇఎం వెకేషన్
257,"12/28/23, 21:16 -",A,Mari,మరి
258,"12/28/23, 21:16 -",A,Naa kosamu ani sollu,నా కోసము అని సొల్లు
259,"12/28/23, 21:16 -",A,Chepavu,చేపవు

In [59]:
df4.to_csv('pra_2.csv')

In [ ]:
save_directory = "/home/user/Documents/ML_DL_PROJECTS/WhatsAppChatAnalysisProject/artifacts"

In [ ]:
loaded_model = AutoModelForSeq2SeqLM.from_pretrained(save_directory)
loaded_tokenizer = AutoTokenizer.from_pretrained(save_directory)

In [8]:
def translator(df):
    save_directory = "/home/user/Documents/ML_DL_PROJECTS/WhatsAppChatAnalysisProject/artifacts"
    loaded_model = AutoModelForSeq2SeqLM.from_pretrained(save_directory)
    loaded_tokenizer = AutoTokenizer.from_pretrained(save_directory)    
    obj = pipeline('translation', model=loaded_model, tokenizer=loaded_tokenizer, src_lang="tel_Telu", tgt_lang='eng_Latn', max_length = 10000)
    outputs = []
    for i in range(len(df)):
        output = obj(df.loc[i]['translit_msgs'])
        outputs.append(output[0]['translation_text'])
    df['translate_msgs'] = outputs
    return df

In [66]:
df5 = df4.copy()

In [9]:
df5 = pd.read_csv('pra_2.csv')

In [12]:
df5 = df5.drop('Unnamed: 0',axis=1)

In [13]:
df5 = translator(df5)

In [27]:
df5.to_csv('pra_3.csv')

In [28]:
df5.head()

,message_date,users,messages,translit_msgs,translate_msgs
0,"12/27/23, 21:36 -",A,Ok,ఒక్,"Oh, my God."
1,"12/27/23, 21:36 -",B,Nedhi aipoyaka,నేది అయిపోయాక,When I was done
2,"12/27/23, 21:36 -",B,Naku cheppu maths..4th chapter,నాకు చెప్పు మాత్స్..౪త్ చాప్టర్,"Tell me, Maths, the fourth chapter."
3,"12/27/23, 21:37 -",B,Okay na...Marchipoku raa nanaa,ఒకే నా...మర్చిపోకు రా ననా,"Just remember, my dear."
4,"12/28/23, 00:03 -",B,Hello,హెల్లో,"Hello, my name is"

In [30]:
df6 = df5.copy()

In [37]:
for i in range(len(df6)):
    if(len(df6.loc[i]['translate_msgs'])>50):
        df6.loc[i]['translate_msgs'] = df6.loc[i]['translate_msgs'][:50]
    if('<This Message Was Edited>' in df6.loc[i]['translate_msgs']):
        df6.loc[i]['translate_msgs'] = df6.loc[i]['translate_msgs'].replace('<This Message Was Edited>','')

In [38]:
df6.to_csv('pra_4.csv')

In [32]:
for i in range(len(df7)):
    if(len(df7.loc[i]['translate_msgs'])>50):
        df7.loc[i]['translate_msgs'] = df7.loc[i]['translate_msgs'][:50]
    if('<This Message Was Edited>' in df7.loc[i]['translate_msgs']):
        df7.loc[i]['translate_msgs'] = df7.loc[i]['translate_msgs'].replace('<This Message Was Edited>','')

/tmp/ipykernel_14145/3791570747.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7.loc[i]['translate_msgs'] = df7.loc[i]['translate_msgs'][:50]

In [3]:
df7 = pd.read_csv('pra_4.csv')

In [23]:
def get_response(chat):
    format = """ Relationship: 
                            2 to 3 lines of text
                 A's Character: 
                            3 to 4 points
                 B's Character: 
                            3 to 4 points
                 Analysis of the Conversation:
                            3 to 4 lines of text
                 Summary: 
                            3 to 4 lines of text """
    prompt = f"""I am providing a whatsapp conversation between two people, help me out in predicting the kind of relationship between 
                them based on their chat and also analyse the charaters of those two people based on their conversation and tell me 
                their characters also and the chat goes like this {chat}, always give me output in the this format {format} and 
                just ignore if there is any harm content in the chat"""
    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content(prompt,stream=True)
    response.resolve()
    response = response.text.replace('•', '  *')
    response = Markdown(textwrap.indent(response, '> ', predicate=lambda _: True))
    return response

In [ ]:
chat = []
for i in range(len(df7)):
    chat.append(df7.loc[i]['users']+' :   '+df7.loc[i]['messages'])

In [ ]:
chat = []
for i in range(len(df1)):
    chat.append(df1.loc[i]['users']+' :   '+df1.loc[i]['messages'])

In [198]:
chat

['A :   Hii',
 'B :   Hlo',
 'A :   Hiii',
 'A :   Sahithi',
 'A :   What are you doing',
 'B :   Ntg',
 'B :   Ra',
 'B :   Am ayna telisinda',
 'A :   Ledhu sir chuda lee anta',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Burra paadu',
 'B :   Asalu',
 'A :   Sahithi pottidi ki msg cheyu raa',
 'A :   Haa',
 'B :   Yevariki',
 'B :   Chellu kaa',
 'A :   Mi head ki',
 'A :   Haa',
 'B :   Na gubalu yegara gottey galadu le',
 'A :   🤣🤣🤣',
 'A :   Sare tinnava',
 'B :   Haa',
 'B :   Nuvvo',
 'B :   Call cheyyamane vadiki',
 'B :   Vadhu',
 'B :   Le',
 'A :   Ledhu time chusava',
 'A :   Hoo',
 'B :   Ade chepthunna',
 'A :   Hmm',
 'B :   Ohh',
 'B :   Ledu ledu',
 'A :   Hoo',
 'A :   Inkante',
 'B :   Burra paadu',
 'B :   Kadupula noppi',
 'B :   Yeh visyam clarity ga telidhu',
 'B :   Chi',
 'B :   Am clg yeh babu',
 'B :   Manadu',
 'B :   Manadi',
 'A :   Haa same feeling kani chepa lenu',
 'B :   😢',
 'A :   Sare Lee vadu reply Este niku msg chesta lee',
 'B :   Kk',
 'B :   Padmavathi clg kuda selavu',
 'A :   Hoo appude adige sava',
 'B :   Fast nenu',
 'B :   Selavu manaki kuda',
 'B :   Tomorrow (05.12.23) college holiday',
 'A :   S',
 'A :   Super',
 'B :   Am antha badha',
 'A :   Arey maa Chelli pettamandi petta',
 'A :   Niku badha ante CLG tmrw holiday estaro ledho ani',
 'B :   Nakaa',
 'A :   Ledhu naku ani pettali kani mistake',
 'B :   Ohh',
 'B :   Me chelli ki echara',
 'B :   Selavu',
 'A :   Haa',
 'B :   Hi',
 'B :   Chadivesava',
 'A :   Ledhu',
 'A :   Tmrw holiday estaro amo ani balance uncha',
 'B :   Evvaru mari',
 'A :   Hoo sare evvaku pothe ledhu',
 'A :   Ante',
 'B :   Jyothi akka vallu bojanam ki pilichara meku',
 'A :   Epudu',
 'B :   Repu',
 'A :   Emo naku telidhu',
 'B :   Me mummy ki adigi cheppu',
 'A :   Sare kani',
 'A :   Nuvvu chadesava',
 'B :   Ledu ra',
 'B :   Bayam vesthundi',
 'B :   Naku',
 'A :   Hoo',
 'B :   Haaa',
 'B :   Send me',
 'B :   Today',
 'B :   Holiday',
 'B :   Msg chudu grouplo',
 'A :   Hoo super raa',
 'B :   Orey',
 'B :   Bojanalaki vasthava',
 'B :   Shake',
 'A :   Hiii',
 'A :   Tinnava',
 'B :   Hi',
 'A :   Hiii',
 'B :   Hlo',
 'B :   Aishu',
 'B :   💯',
 'A :   😍😍',
 'B :   Nice',
 'A :   😚😚',
 'A :   Arey EDI oka sari chudu',
 'B :   Ila vuntundi aa',
 'A :   Haa',
 'A :   Epudu Mari pondi',
 'B :   Enti',
 'B :   Pondi enti ra',
 'A :   Epudu Mari poindhi  raa',
 'B :   Baledu antunnava',
 'B :   Ma intlo chala long antunnaru',
 'A :   Ledhu raa super ga chesaru antunna',
 'A :   Hoo',
 'B :   Avunu',
 'A :   Emo time undi kadha chudam',
 'B :   Haa sare le',
 'A :   Hmm',
 'A :   Arey balloons ne phone lo order cheyu raa',
 'A :   Epudu cheste aapudo vastadi',
 'B :   Na phone lo nenu yeppudu pettaledu ra',
 'B :   Ne phone lo petti money kavalante echestha',
 'B :   Aishu ma nanna money adigaru ra',
 'A :   Arey 350 ani chepamannadi taruvata chudam annadu',
 'A :   Ok na',
 'B :   Yevaru',
 'A :   Ma mom',
 'B :   Adi kaadu yeh babu',
 'A :   Mari enti',
 'B :   Cheppuluvi, kit vi',
 'A :   Enti ardham kaledhu',
 'A :   Phone cheyyala',
 'B :   Cheppulu',
 'B :   Baby kit usha valla babu ki teesukunnam kada',
 'B :   Aa money',
 'A :   Haa sare',
 'B :   Nenu raanu ra',
 'A :   Em',
 'B :   Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru',
 'A :   Hoo',
 'B :   Haaa',
 'A :   Sare kani money anta',
 'B :   280 ra',
 'B :   Monna 50 icha annav kada',
 'B :   230',
 'A :   Haa kk',
 'B :   Haa sare',
 'B :   🙏🏻',
 'B :   Y',
 'A :   Song baledha',
 'B :   Super',
 'A :   Anduke petta reasons em ledhu',
 'B :   Aishu pettava photo',
 'B :   Enti ra',
 'A :   Hii sahithi',
 'B :   Hi ra',
 'B :   Photo pettava',
 'A :   Haa pedata lee',
 'B :   Sry raledu endhuku ante dress change cheyledu',
 'B :   Andhuke',
 'A :   Paravaledu lee',
 'A :   Akhila kavi vacharu',
 'B :   Marchipoku e roju pettu',
 'B :   Avunaa',
 'A :   Haa',
 'B :   Videos pettu',
 'B :   Naku',
 'B :   Puja vi',
 'A :   Haa',
 'B :   Aishu pettava',
 'B :   Photo',
 'A :   Haa',
 'B :   Am annaru',
 'B :   Oley hd vi pettamani cheppa kadey',
 'B :   🫢',
 'B :   Hi',
 'A :   Hii',
 'B :   Chadivesava madam',
 'A :   Ledhu raa maths main chudali',
 'B :   Chusava mari',
 'A :   You deleted this message',
 'B :   Chadivesava',
 'A :   Ledhu',
 'B :   Nv brilliant le appudu kappudu ayna chusi rasesthav',
 'A :   Haa avunu lee',
 'B :   Yes its true',
 'B :   Aishu e question chadivava',
 'A :   Nanu asalu em chadavale',
 'B :   Avunaa',
 'B :   Sare le',
 'A :   Hmm',
 'B :   Send me',
 'B :   Aishu',
 'B :   Adigava',
 'B :   Vallaki  am annaru',
 'A :   Avariki',
 'B :   Anu monika mani vallaki',
 'A :   Haa kk moni , rama',
 'A :   Anu kudha m avvaka pote  annadi',
 'A :   Hii',
 'B :   Hii',
 'B :   Hi',
 'A :   Hiii',
 'B :   Am doing',
 'A :   Hiii',
 'B :   Hi',
 'A :   Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa',
 'B :   Rama raadhu aa',
 'A :   Ante mrng varuku telidhu',
 'B :   Am alaga',
 'A :   Emo',
 'B :   Avuna',
 'A :   Hmm',
 'B :   Inko 4members yevaru ra',
 'A :   Chinnamudu , paiga vallu avaro anta family nee',
 'B :   Ohh kk le',
 'A :   Hmm',
 'A :   Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali',
 'B :   Sare',
 'A :   Sare inka',
 'B :   Cheppali',
 'A :   Ante tmrw kosam adaina cheppu',
 'B :   Games aa',
 'A :   Haa',
 'B :   Okka 5min aaagu',
 'B :   Msg chesthanu',
 'A :   Kk',
 'B :   Yeh dress vesthav',
 'A :   Nenu birthday di anukuntunna u',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Mari nenu am veyyali',
 'B :   Authe',
 'A :   Emo nuvve Alo chinchu',
 'B :   Cheppu nuvvu',
 'A :   Naku ala telustunndi',
 'B :   Na dresslu anni chusav kada',
 'A :   Emo raa nuvve decide avvu',
 'B :   Sare le',
 'B :   Edi ok naa',
 'A :   Haa kk',
 'B :   Kk le',
 'A :   Hmm',
 'B :   Leka pothe inko top vundi',
 'A :   Ado',
 'B :   Kothadi adi ayna vadesthanu le',
 'A :   Haa ne estam nee dress',
 'B :   Sare le',
 'A :   Hmm',
 'B :   Inkem games adugu mani vallaki',
 'A :   Hiii sahi',
 'A :   Anu ki phone cheyu oka sari adugu',
 'B :   Sare',
 'B :   Hi',
 'B :   Enni gantalaki ra',
 'B :   Aishu phone pay number pettu money phone pay chestha',
 'A :   9949437849',
 'A :   Kk naa',
 'B :   Kk',
 'B :   Orey phone pay maadi avvatledu limit aypoyindi madi e roju di',
 'B :   Mrng thechi echesthanu me daddy ki cheppu',
 'A :   Kk',
 'B :   Evena pics mari levaa',
 'A :   Haa rassu ki cheppa',
 'A :   Tana daggara konni vunnay',
 'A :   Oka sari nuvvu msg pettu',
 'B :   Kk',
 'B :   Hi',
 'A :   Hiii',
 'A :   🤣🤣',
 'B :   😂',
 'B :   Date chusava',
 'A :   Sahithi nee English key nadaggara vundi',
 'B :   Ade vethika',
 'B :   Chala sepu',
 'A :   Hoo nenu epudo msg petta',
 'B :   Mobile vundadu ani telusu gaa neku',
 'B :   12th answer pettava',
 'B :   Tqqq❤️😘🥰',
 'A :   Abho chalu lee',
 'B :   😄',
 'B :   Open chesava',
 'B :   Set',
 'A :   Haa chusa',
 'A :   Pump evvale ante',
 'A :   Anni kk',
 'B :   Evvaleda pump',
 'A :   Ledhu',
 'B :   Kkk',
 'B :   Aishu',
 'B :   Aishu',
 'B :   Photo pettu',
 'A :   Aa photo',
 'B :   Frame',
 'A :   Pack chesadhu vadu',
 'B :   Avuna',
 'B :   Nv kuda chudaledha',
 'A :   Hmm',
 'A :   Ledhu',
 'B :   Indhaka yekkadiki vellav',
 'B :   Gift kosam aa',
 'A :   Sorry wrong answer pakodi kosam',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Gift konta annav',
 'A :   Haa tmrw suprise miku ,anu ki kudha',
 'B :   Nku cheppu le',
 'B :   Parledu',
 'A :   Tmrw chustav kadha',
 'B :   Cheppu',
 'B :   Ra',
 'A :   Bye muggulu chustunna',
 'B :   Cheppava',
 'B :   Anthe n',
 'B :   Nenu neku telisinatte chesa ga yedi chesinaa',
 'B :   Edi cheating asalu',
 'A :   Ledhu raa inka em konalo decide avvale anduke',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Aishu',
 'B :   Aishu chude yelaga chesado',
 'B :   Chala kopam ga vundi vaadi medha',
 'A :   Haa delete kudha cheya lee',
 'B :   Cheyyadu vaadu nku telusu',
 'A :   Haa Mari em chestam nenu , nuvvu kudha chudale',
 'A :   Hmm',
 'A :   Arey cake kosam money enta',
 'A :   Cheppa lee',
 'A :   Sare anu status chusava',
 'B :   Me estham yeh',
 'B :   Vaadu inka delete cheyleda',
 'B :   Naku chala chiraku ga vundi',
 'B :   Anu kuda status pettisindi',
 'B :   Vinu',
 'B :   Aishu',
 'A :   Tmrw chemistry bullet evvu',
 'A :   Arey msg cheyu tanuja ki',
 'A :   Plss',
 'B :   Kk',
 'A :   Arey manam Ela nee epudaina photos tesukundam kk naa',
 'B :   Done done 👍👍👍',
 'A :   Sare chemistry photos pettu',
 'B :   Ammo chadivedham ane',
 'A :   Haa kani epudu di ee paper',
 'B :   Repatiki',
 'B :   Hiiii',
 'B :   Hi',
 'B :   Ame',
 'A :   Arey EDI accident naku estam raa ee movie lo',
 'A :   Naa kallu Edo chepuko']

In [200]:
person1

'ysrfoundation2'

In [199]:
get_response(chat)

> **Relationship:**
>
> The relationship between A and B appears to be friendly and casual, possibly between friends or acquaintances. They communicate in a familiar manner, using nicknames and emojis, and discuss everyday topics such as activities, plans, and personal updates.
>
> **Character Analysis:**
>
> **A:**
>
> - Outgoing and friendly: A initiates conversations, uses playful language, and expresses enthusiasm.
> - Organized and detail-oriented: A often asks for specific information and follows up on requests.
> - Considerate and accommodating: A shows concern for B's feelings and tries to accommodate their preferences.
>
> **B:**
>
> - Relaxed and easy-going: B responds calmly to A's questions and requests, and does not seem to get stressed or agitated.
> - Open to suggestions and willing to help: B agrees to carry out tasks and requests made by A.
> - Playful and humorous: B uses emojis and jokes to add a lighthearted tone to the conversation.
>
> Overall, A and B seem to have a positive and comfortable relationship, characterized by mutual respect and a sense of camaraderie.

In [45]:
f = open('dataset/WhatsApp Chat with NAGA JYOTHIKA (MBIPC NZD).txt','r',encoding='utf-8')

In [46]:
chat1 = f.read()

In [47]:
chat2 = chat1.split('\n')

In [48]:
chat2

['A: Hello,Beee exam raayaledha?',
 'B: Ledhu',
 'B: Why?',
 'A: 9th chart photos vunnaya?',
 'B: Ledhu',
 'A: Sarle...',
 'B: Ha',
 'A: Poni chart vundha?',
 'A: Twaraga cheppu..',
 'B: Haa',
 'B: Undhi',
 'A: Ivvagalava 9th chart practice chesi istha...',
 'B: Sare',
 'B: Ekkada unnav',
 'A: Sare nenu counter dhaggara vunta theeskoni ra',
 'B: Haa',
 'B: Ok correct diagram unte pettu',
 'B: Chuskunta',
 'A: Kk',
 'A: Actually, nenu naa clz okadiki photos pettamanna, nee dhaggara chart theeskunna tharvaatha vaadu pettaadu, andhulondhe ee diagram',
 'B: Oh ok',
 'B: Hello',
 'B: Ipoyindha?',
 'A: Yeah',
 'A: 5 mins thintunna',
 'B: Oh ok',
 'A: Vachaaka istha',
 'B: Vachaka msg chey',
 'B: Ok',
 'B: 9th chart lo 3rd question pic unte pettava',
 'A: sorry for delay...',
 'B: Tq no problem',
 'B: 10 th dhi kuda pettava',
 'A: Ok👍',
 'B: K tq',
 'A: Hello, repu camp ki velthunnaara?',
 'B: Nope',
 'B: Hey..tnx',
 'A: Vellatle...',
 'A: Sem ana...',
 '1B: Yeah',
 'A: Entha madhi velthunnaaru?',
 'B: Velle vallu ithe 23 veltharu anta',
 'B: Max velthunnaru',
 'B: Oka 2 or 3 vellatle anthey',
 'A: Mari next time vellataaniki neeku avuthundha?',
 'A: Jrs tho',
 'B: Chance undha mam ani adiganu..kunukkunta annaru',
 'B: If unte chestha ledhante drop out eh',
 'A: Avna, c cirtificate voddha?',
 'B: Certificate akkarledh le experience chaalu',
 'A: 5% marks aanta, nuvvu aa govt exam raaaina?',
 "B: That's okay",
 'B:But 5% kosam ippudu stress thisko dhalchukoledhu',
 'A: Sarle, marks emivundhi le kastapadithe 100% kooda vasthaayi, ...',
 'B: Haa avnu',
 'A: Assalu stress theeskomaaku,Gudnyt, take care,Bye..',
 'B: Haa',
 'B: Good night',
 'B:Byee',
 'A: Mee question paper send chey',
 'A: So late,By now I solved half paper,...',
 'B: 🥲exam sarigga rayale so mummy tho matladuthu chudale',
 'B: Ok le anyway all theBest 👍',
 'A: No worries, idhi oka exam aa kaadhu naaku,...',
 'A: Vodhiley inka dhaanni,..',
 'B: Haa sare',
 '']

In [49]:
get_response(chat2)

> **Relationship:**
>
> The relationship between A and B is that of friends or classmates who are preparing for an exam together. They discuss exam preparation, exchange photos of charts and diagrams, and help each other out with practice questions.
>
> **A's Character:**
>
> A is a serious and responsible person who is focused on exam preparation. They are organized and efficient, and they like to have a plan. They are also helpful and willing to share their resources with others.
>
> **B's Character:**
>
> B is a more relaxed and easy-going person than A. They are also helpful and willing to share their resources, but they are not as focused on exam preparation as A. They are more interested in enjoying the process and having fun.
>
> **Analysis of the Conversation:**
>
> The conversation begins with A asking B if they have received a photo of a chart for the 9th exam. B replies that they have not, and A expresses disappointment. A then asks if B has any other charts, and B replies that they do have one. A requests B to send the chart so that they can practice, and B agrees.
>
> The conversation then turns to the upcoming exam camp, and A asks B if they are planning to attend. B replies that they are not, and A expresses disappointment. B explains that they have not received any information about the camp, but they will try to find out more.
>
> The conversation ends with A sending B a practice question and asking for their help in solving it. B agrees to help, and they wish each other good night.
>
> Overall, the conversation is friendly and cooperative, and it suggests that A and B have a good relationship.

In [104]:
df = pd.read_csv("dataset/pra_4.csv")

In [105]:
chat = []
for i in range(len(df)):
    chat.append(df.loc[i]['users']+' :   '+df.loc[i]['messages'])

In [11]:
chat

['A :   Ok',
 'B :   Nedhi aipoyaka',
 'B :   Naku cheppu maths..4th chapter',
 'B :   Okay na...Marchipoku raa nanaa',
 'B :   Hello',
 'B :   Good morninguu',
 'A :   Good morningu',
 'B :   Doubts adugudhamani ankunnanu',
 'A :   Ossey',
 'B :   ippudu antha intrest Ledhu ra naku',
 'B :   ippudem adaganle',
 'A :   Haiga',
 'A :   Vachinavi',
 'A :   Rasi',
 'A :   Raa.',
 'B :   naku gauss forward method meedha problems',
 'B :   naku pics pettu',
 'B :   mrng oka sari chustha',
 'B :   inka nak opika ledhu',
 'A :   Mrng lepu',
 'A :   Pedutha',
 'B :   leputhanle',
 'B :   ennintiki',
 'A :   Okay..',
 'A :   6',
 'B :   okay',
 'B :   ippudu pettochu ga',
 'B :   sare….nek velainapppudu pettu mrng lopu',
 'B :   chuskunta',
 'A :   Ok',
 'A :   Jyo..',
 'B :   Good nightuu prashu baabu',
 'A :   ❣️❣️',
 'A :   Good bye',
 'A :   Vey. .',
 'A :   Nenu hurt avina',
 'A :   Inka no calls',
 'B :   Em raaa',
 'B :   Prashu baabu',
 'A :   Anthae',
 'A :   Mari inka',
 'A :   Hurted',
 'B :   Emaindhi',
 'B :   Malli',
 'A :   Break up',
 'A :   U and me',
 'A :   Bye baby inka',
 'B :   No..no....no <This message was edited>',
 'B :   Ala cheppaku',
 'A :   Alane',
 'A :   Chebutha',
 'A :   Inka bye baby neku..',
 'B :   No...no',
 'B :   Arey....evng',
 'A :   Tffr sry for',
 'A :   Disturbing',
 'B :   🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻',
 'A :   Sadvukoo',
 'B :   Tffr anaku ra baabu',
 'A :   Nijjamu',
 'A :   Ga',
 'B :   Sadavdaniki raledhule...nenu',
 'A :   Adhukee',
 'B :   Oorke vacha...Evng varku undi velipodham ani',
 'A :   Sollu chepaku',
 'A :   Ala',
 'B :   Evng order vasthadhi',
 'B :   Adhi collect cheskuni podham ani',
 'A :   Chee',
 'A :   Order ki',
 'B :   🤦🏻\u200d♀️🤦🏻\u200d♀️🤦🏻\u200d♀️',
 'A :   Nanu ramani',
 'A :   Kooda',
 'A :   Analedu',
 'B :   ....',
 'A :   Nuv oka danivi',
 'B :   Cheppelopu aagithunnavaa',
 'A :   Velutunavu',
 'A :   Good bye. .',
 'A :   Cover up..',
 'B :   Chepthunte...',
 'B :   Nijam ra...start chesa...evng ani...elopu topper saduko antunnav',
 'A :   Sollu',
 'A :   Good bye',
 'A :   Neku naku',
 'B :   Chat chaduvu',
 'B :   Okasari',
 'B :   Sachinodaa',
 'A :   Matalu levu',
 'A :   Inka',
 'B :   Raavaa....?',
 'A :   Neku cutted',
 'A :   Inka neku naku',
 'B :   No',
 'A :   No blood relations',
 'B :   Muskuni raa anthe',
 'B :   Avnu leBlood relation ledhu',
 'A :   Chii',
 'A :   Ekada kooda',
 'A :   Ledhu ani',
 'A :   Chepinavu',
 'A :   Nanu',
 'A :   Veru chesi',
 'B :   Blood relation ela untadhi ra manaki',
 'A :   Chebutunavu',
 'A :   Lekpothe bed relationship vundha 🙄?',
 'B :   Nedhi eh blood group',
 'A :   Inka',
 'A :   Evi vodule',
 'B :   Chpu raa',
 'A :   Diversions',
 'A :   Madyalo',
 'A :   Gb baby 👶',
 'B :   Nenem divert chesanu',
 'A :   ..',
 'B :   Ha....adiga...',
 'B :   Blood relation ledhu annav ga',
 'B :   Andhuke adiga',
 'A :   Sarle tffr sorry bye',
 'A :   Nenu emi',
 'B :   Nv saduvkovalaa',
 'A :   Adganule. ..',
 'A :   Nuv',
 'A :   Lib lo vundhi',
 'A :   Tffr sadvuko sollu',
 'A :   Edhuku',
 'A :   Mali nannu',
 'B :   Nen em sadavatledhlee',
 'A :   Antavvu',
 'A :   Sorry',
 'A :   For disturbance',
 'A :   Good bye',
 'B :   OreyyyNen 2 gantalu lib lo unna kooda tappenaa',
 'B :   Nvem disturbance kadhule naku',
 'A :   U r wish',
 'A :   Nenu',
 'A :   Emi annaule inka',
 'A :   Sorry',
 'B :   Oyee',
 'A :   Akka. .',
 'B :   Inka ekkuva cheyku',
 'A :   Good bye',
 'A :   Inka mali',
 'B :   No',
 'A :   Nenu edho okati antannu',
 'A :   Nenu',
 'A :   Chat chesi daggra nuchi',
 'B :   Parvaledhu',
 'A :   Good bye 💔🙏🙄\U0001fae0',
 'B :   Naku',
 'B :   No problem for me',
 'B :   🙄🙄🙄',
 'A :   👎💔💔😭',
 'B :   ☹️☹️☹️',
 'A :   😶😶😶',
 'B :   Mothaniki....adigindanki cheppaledhu',
 'B :   Nv',
 'A :   Inka naku',
 'A :   Samadhamu',
 'A :   Ledu',
 'A :   Nuv chepaku emi',
 'A :   Naku',
 'B :   Em sambandham ledhu',
 'A :   Nenu chepanu',
 'A :   Good bye',
 'A :   Em ledu',
 'B :   Cheppu',
 'B :   ☹️☹️',
 'B :   Prashu baabu',
 'B :   😶😶😶',
 'B :   🤕🤕🤕',
 'A :   I am died',
 'B :   Arey...nanaa',
 'A :   Good bye..',
 'B :   Nooo',
 'A :   nana',
 'A :   Anaku',
 'A :   😡😡',
 'B :   ChollyyyyyPrashu',
 'A :   Inka. .',
 'A :   Sorry jyothirm💔i',
 'B :   Endhuku ra',
 'B :   Sare.....Evng vasthava...rava... edho okati cheppu',
 'A :   No comments',
 'A :   Neku naku',
 'A :   Sambadhamu',
 'B :   Just sayYes or no',
 'A :   Ledu cutted',
 'B :   ....',
 'A :   No comments',
 'A :   Good bye',
 'A :   💔💔😡',
 'B :   Sare....ne istam',
 'B :   Nene pothanle',
 'A :   Good 💔💔😡',
 'A :   Bye',
 'A :   Jyothirm💔i akka',
 'B :   😶😶😶',
 'A :   Sry',
 'A :   For disturbing',
 'A :   Marchipoyi',
 'A :   Chesale',
 'A :   No calls inka',
 'A :   Nenu chesinapudu nuve lift cheyaku nuv chesinapudu nenu kooda lift cheyanule..',
 'A :   Bye baby',
 'B :   Endhuku baby ala antav',
 'A :   Anthae inka',
 'A :   Break up baby',
 'A :   😶😶😭😭🤧',
 'A :   Ice cream eppichu',
 'A :   Vey elagoo lib lo vunavu ga fc pakkanega',
 'B :   Night ki vasthava mari',
 'B :   Fc ki',
 'A :   Okay. .',
 'B :   Okay',
 'A :   Break up',
 'A :   Aidhi ga',
 'A :   Na mokkamu ela chupchali',
 'A :   Neku...',
 'B :   Avvaledhu',
 'B :   So...no problem',
 'A :   Sare aithey vasthale',
 'B :   Okay',
 'A :   🤤🤤🤤🤤',
 'B :   Time chepthe... vastha nenu',
 'A :   Chepu',
 'B :   Uhh',
 'B :   Eppudu Nene chepthaa',
 'B :   Ippudu nv chepthe nen vastha',
 'A :   U',
 'A :   Cheppu',
 'A :   Nenu cheppaka pothe ravu ga',
 'A :   Aithey',
 'A :   Chi po vey <This message was edited>',
 'A :   Jyo baby 🍼👶',
 'B :   Hloo',
 'B :   Prashu baabu',
 'B :   Nv eppudu free ante appude',
 'A :   Nenu',
 'A :   Always',
 'A :   Free jyo..',
 'B :   Abboo',
 'B :   Sare',
 'B :   1 or 2 cheppu',
 'A :   2',
 'B :   Aithey...7.30',
 'B :   Okay ga..neku',
 'A :   Okay..',
 'B :   Heloo',
 'A :   Ha',
 'B :   Em chesthunnav baabu',
 'A :   Phn chustuna',
 'A :   Paddukoni',
 'B :   SarleNen vachesthunna',
 'B :   Daddy ki theskunnan ra',
 'A :   En',
 'A :   Em vacation',
 'A :   Mari',
 'A :   Naa kosamu ani sollu',
 'A :   Chepavu']

In [29]:
def get_response(chat):
    format = """ Relationship: 
                            2 to 3 lines of text
                 A's Character: 
                            3 to 4 points
                 B's Character: 
                            3 to 4 points
                 Analysis of the Conversation:
                            3 to 4 lines of text
                 Summary: 
                            3 to 4 lines of text """
    prompt = f"""I am providing a whatsapp conversation between two people, help me out in predicting the kind of relationship between 
                them based on their chat and also analyse the charaters of those two people based on their conversation and tell me 
                their characters also and the chat goes like this {chat}, always give me output in the this format {format} and 
                just ignore if there is any harm content in the chat"""
    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content(prompt,stream=True)
    response.resolve()
    # response = response.text.replace('•', '  *')
    # response = Markdown(textwrap.indent(response, '> ', predicate=lambda _: True))
    return response

In [75]:
response = get_response(chat)

In [77]:
response.text

"Relationship: Friends or Colleagues\n\nA's Character:\n\n- Friendly and easy-going: Uses emoticons and informal language, shows concern for B's well-being.\n- Humorous and playful: Makes jokes and uses playful language.\n- Supportive and encouraging: Offers help and encouragement to B.\n\nB's Character:\n\n- Appreciative and grateful: Thanks A for their help and support.\n- Trusting and open: Shares personal information with A.\n- Polite and respectful: Uses polite language and shows appreciation for A's efforts.\n\nAnalysis of the Conversation:\n\n- The conversation is casual and friendly, with both A and B using informal language and emoticons.\n- They share personal information and offer each other support and encouragement, indicating a close and supportive relationship.\n- The conversation is focused on B's upcoming trip, suggesting that A is supportive of B's plans and interests.\n\nSummary:\n\nA and B have a friendly and supportive relationship, likely as friends or colleagues. They are comfortable sharing personal information with each other and offer each other encouragement and support. The conversation suggests that they have a close and supportive bond."

In [37]:
li = response.text.split('\n')

In [38]:
li[0]

'Relationship: The relationship between A and B appears to be friendly and casual. They share a comfortable level of communication and use informal language.'

In [45]:
li

['Relationship: The relationship between A and B appears to be friendly and casual. They share a comfortable level of communication and use informal language.',
 '',
 "A's Character:",
 '- Friendly and approachable: Uses warm and colloquial language.',
 '- Humorous: Makes lighthearted jokes and uses emojis.',
 "- Caring: Expresses concern for B's well-being.",
 "- Curious: Asks questions and shows interest in B's activities.",
 '',
 "B's Character:",
 '- Open and communicative: Shares personal thoughts and feelings.',
 "- Appreciative: Expresses gratitude and recognizes A's efforts.",
 '- Supportive: Offers encouragement and understanding.',
 "- Inquisitive: Asks questions and shows interest in A's life.",
 '',
 'Analysis of the Conversation:',
 '- The conversation is characterized by a positive and supportive tone.',
 '- Both A and B actively engage in the conversation, contributing equally.',
 '- They share personal anecdotes and experiences, indicating a level of trust and familiarity.',
 '- The use of emojis and informal language suggests a casual and comfortable relationship.',
 '',
 'Summary:',
 'A and B have a friendly and supportive relationship. They communicate openly and share personal experiences. Their conversation is characterized by humor, care, and mutual interest. The casual and informal nature of their communication suggests a comfortable level of connection.']

In [39]:
li[2]

"A's Character:"

In [ ]:
0->relationship

In [46]:
li.index("A's Character:")

2

In [47]:
li.index("B's Character:")

8

In [48]:
li.index('Analysis of the Conversation:')

14

In [49]:
li.index('Summary:')

20

In [50]:
rel_li = li[0]

In [52]:
rel_li[14:]

'The relationship between A and B appears to be friendly and casual. They share a comfortable level of communication and use informal language.'

In [56]:
a = li[li.index("A's Character:")+1:li.index("B's Character:")-1]

In [57]:
a

['- Friendly and approachable: Uses warm and colloquial language.',
 '- Humorous: Makes lighthearted jokes and uses emojis.',
 "- Caring: Expresses concern for B's well-being.",
 "- Curious: Asks questions and shows interest in B's activities."]

In [58]:
b = li[li.index("B's Character:")+1:li.index('Analysis of the Conversation:')-1]

In [59]:
b

['- Open and communicative: Shares personal thoughts and feelings.',
 "- Appreciative: Expresses gratitude and recognizes A's efforts.",
 '- Supportive: Offers encouragement and understanding.',
 "- Inquisitive: Asks questions and shows interest in A's life."]

In [62]:
aoc  = li[li.index('Analysis of the Conversation:')+1:li.index('Summary:')-1]

In [63]:
aoc

['- The conversation is characterized by a positive and supportive tone.',
 '- Both A and B actively engage in the conversation, contributing equally.',
 '- They share personal anecdotes and experiences, indicating a level of trust and familiarity.',
 '- The use of emojis and informal language suggests a casual and comfortable relationship.']

In [64]:
soc = li[li.index('Summary:')+1:]

In [66]:
li[len(li)-1]

'A and B have a friendly and supportive relationship. They communicate openly and share personal experiences. Their conversation is characterized by humor, care, and mutual interest. The casual and informal nature of their communication suggests a comfortable level of connection.'

In [97]:
def get_response(chat):
    # format = """ Relationship: 
    #                         2 to 3 lines of text
    #              Character of A: 
    #                         3 to 4 points
    #              Character of B: 
    #                         3 to 4 points
    #              Analysis and Sentiment of the Conversation:
    #                         3 to 4 lines of text
    #              Summary: 
    #                         3 to 4 lines of text """
    format = """['Relationship', 'Character Analysis of A', 'Character Analysis of B', 'Analysis and Sentiment of the Conversation', 'Summary']"""
    prompt = f"""I am providing a whatsapp conversation between two people, help me out in predicting the kind of relationship between 
                them based on their chat and also analyse the charaters of those two people based on their conversation and tell me 
                their characters also and the chat goes like this {chat}, make sure you always give me output exactly in the this format {format} and 
                just ignore if there is any harm content in the chat"""
    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content(prompt,stream=True)
    response.resolve()
    # rel = model.generate_content(f"fetch text associated with relationship from the given text {response.text}",stream=True)
    # a = model.generate_content(f"fetch text under character of A from the given text {response.text}",stream=True)
    # b = model.generate_content(f"fetch text under character of B from the given text {response.text}",stream=True)
    # aoc = model.generate_content(f"fetch text under analysis and sentiment of the conversation from the given text {response.text}",stream=True)
    # soc = model.generate_content(f"fetch text under summary of the conversation from the given text {response.text}",stream=True)
    # rel.resolve()
    # a.resolve()
    # b.resolve()
    # aoc.resolve()
    # soc.resolve()
    # rel = rel.text
    # a = a.text
    # b = b.text
    # aoc = aoc.text 
    # soc = soc.text
    # print(a,b,aoc,soc)
    # return a,b,aoc,soc
    print(response.text)
    return response.text
    # li = response.text.split('\n')
    # rel = li[0][14:]
    # A = li[li.index("Character of A:")+1:li.index("Character of B:")-1]
    # a = ''
    # for i in A:
    #     a += i+'\n'
    # B = li[li.index("Character of B:")+1:li.index('Analysis and Sentiment of the Conversation:')-1]
    # b = ''
    # for i in B:
    #     b += i+'\n'
    # AOC  = li[li.index('Analysis and Sentiment of the Conversation:')+1:li.index('Summary:')-1]
    # aoc = ''
    # for i in AOC:
    #     aoc += i+'\n'
    # soc = li[len(li)-1]
    # return rel,a,b,aoc,soc

In [98]:
get_response(chat)

['Relationship', 'Character Analysis of A', 'Character Analysis of B', 'Analysis and Sentiment of the Conversation', 'Summary']

['Casual Acquaintances', 'Not enough information to analyze', 'Not enough information to analyze', 'The conversation is short and superficial, with no indication of a deep or meaningful relationship.', 'The conversation suggests that the two people are not particularly close, and they may not even know each other very well. The conversation is polite but lacks warmth or enthusiasm.']

"['Relationship', 'Character Analysis of A', 'Character Analysis of B', 'Analysis and Sentiment of the Conversation', 'Summary']\n\n['Casual Acquaintances', 'Not enough information to analyze', 'Not enough information to analyze', 'The conversation is short and superficial, with no indication of a deep or meaningful relationship.', 'The conversation suggests that the two people are not particularly close, and they may not even know each other very well. The conversation is polite but lacks warmth or enthusiasm.']"

In [111]:
def get_response(chat):
    prompt = f"""I am providing a whatsapp conversation between A and B. Predict the relationship between them based on their chat and analyze the characters of both individuals. Provide your analysis in the following format:

Relationship: 
    2 to 3 points
Character of A:
    3 to 4 points
Character of B:
    3 to 4 points
Sentiment Analysis:
    3 to 4 points
Summary:
    3 to 4 points

The chat goes like this: {chat}.Please ensure that your output follows this format consistently.Be very certain in maintaining the subheaders in the format provided and don't use anything otherthan those words(Relationship, Character of A, Character of B, Sentiment Analysis, Summary) in subheaders Ignore any harmful content in the chat.
"""

    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content(prompt,stream=True)
    response.resolve()
    li = response.text.split('\n')
    print(li)
    # rel = li[1:li.index("Character of A:")-1]
    # A = li[li.index("Character of A:")+1:li.index("Character of B:")-1]
    # a = ''
    # for i in A:
    #     a += i+'\n'
    # B = li[li.index("Character of B:")+1:li.index('Sentiment Analysis:')-1]
    # b = ''
    # for i in B:
    #     b += i+'\n'
    # AOC  = li[li.index('Sentiment Analysis:')+1:li.index('Summary:')-1]
    # aoc = ''
    # for i in AOC:
    #     aoc += i+'\n'
    # soc = li[len(li)-1]
    # req = [rel,a,b,aoc,soc]
    # return rel,a,b,aoc,soc
    # for i in range(len(req)):
    #     req[i] = req[i].replace('A',person1)
    #     req[i] = req[i].replace('B',person2)
    # return req[0],req[1],req[2],req[3],req[4]
    return li

In [112]:
li = get_response(chat)

['Relationship:', '- Friends or acquaintances who share a casual relationship.', '- A disconnect or disagreement is evident in their communication.', '', 'Character of A:', '- Emotional and reactive: expresses a range of emotions, including hurt, anger, and sadness.', '- Impulsive: reacts quickly and without much thought.', '- Possessive and demanding: expects attention and loyalty from the other person.', '- Hurt and feels betrayed.', '', 'Character of B:', "- Defensive and dismissive: often avoids or downplays the other person's feelings.", '- Distracted and uninterested: shows a lack of attention and engagement in the conversation.', "- Non-committal and evasive: doesn't provide clear answers or commitments.", '- Tries to move on despite confrontations and emotional turmoil.', '', 'Sentiment Analysis:', '- Hurt and disappointment: A expresses feelings of hurt and disappointment towards B.', "- Frustration and irritation: B expresses frustration and irritation at A's emotional outbursts.", "- Confusion and misunderstanding: both individuals seem confused and misunderstand each other's intentions and feelings.", '- Emotional turmoil: both A and B experience emotional turmoil and distress.', '', 'Summary:', '- A and B have a strained relationship characterized by emotional outbursts, misunderstandings, and a lack of commitment.', '- A feels hurt and betrayed, while B tries to move on and avoid confrontation.', '- Despite attempts to resolve their issues, they continue to experience emotional turmoil and struggle to find common ground.', '- Both A and B need to communicate more openly and honestly if they want to resolve their differences and move forward.']

In [113]:
li

['Relationship:',
 '- Friends or acquaintances who share a casual relationship.',
 '- A disconnect or disagreement is evident in their communication.',
 '',
 'Character of A:',
 '- Emotional and reactive: expresses a range of emotions, including hurt, anger, and sadness.',
 '- Impulsive: reacts quickly and without much thought.',
 '- Possessive and demanding: expects attention and loyalty from the other person.',
 '- Hurt and feels betrayed.',
 '',
 'Character of B:',
 "- Defensive and dismissive: often avoids or downplays the other person's feelings.",
 '- Distracted and uninterested: shows a lack of attention and engagement in the conversation.',
 "- Non-committal and evasive: doesn't provide clear answers or commitments.",
 '- Tries to move on despite confrontations and emotional turmoil.',
 '',
 'Sentiment Analysis:',
 '- Hurt and disappointment: A expresses feelings of hurt and disappointment towards B.',
 "- Frustration and irritation: B expresses frustration and irritation at A's emotional outbursts.",
 "- Confusion and misunderstanding: both individuals seem confused and misunderstand each other's intentions and feelings.",
 '- Emotional turmoil: both A and B experience emotional turmoil and distress.',
 '',
 'Summary:',
 '- A and B have a strained relationship characterized by emotional outbursts, misunderstandings, and a lack of commitment.',
 '- A feels hurt and betrayed, while B tries to move on and avoid confrontation.',
 '- Despite attempts to resolve their issues, they continue to experience emotional turmoil and struggle to find common ground.',
 '- Both A and B need to communicate more openly and honestly if they want to resolve their differences and move forward.']

In [131]:
rel = li[1:li.index('Character of A:')-1]

In [132]:
rel

['- Friends who have broken up recently.',
 '- They still have feelings for each other, but are trying to move on.']

In [133]:
a = li[li.index('Character of A:')+1:li.index('Character of B:')-1]

In [134]:
a

['- Emotional and impulsive: Expresses intense emotions throughout the conversation.',
 '- Determined to move on from the relationship: Repeatedly says "bye" and tries to cut off communication.',
 '- Has difficulty controlling their emotions: Uses strong language, like "vey" and "illa" to express anger and frustration.',
 '- Tries to maintain a friendly relationship: Uses terms of endearment, like "jyo baby" and "my baby", even after the breakup.']

In [135]:
b = li[li.index('Character of B:')+1:li.index('Sentiment Analysis:')-1]

In [136]:
b

['- Tries to remain calm and rational: Often responds with short, simple answers or emojis.',
 '- Willing to work on the relationship: Suggests meeting up or communicating to resolve their issues.',
 '- Feels hurt and confused by the breakup: Asks "Em sambandham ledhu" (What is our relationship now?) and "Endhuku baby ala antav" (Why are you calling me baby?).',
 '- Tries to maintain a friendly relationship: Also uses terms of endearment, like "naanna" and "prashu baabu", even after the breakup.']

In [137]:
aoc = li[li.index('Sentiment Analysis:')+1:li.index('Summary:')-1]

In [138]:
aoc

['- Mostly negative: The conversation is filled with expressions of anger, sadness, and hurt.',
 '- Some positive moments: There are a few brief instances of positivity, such as when they reminisce about happy memories.']

In [139]:
soc = li[li.index('Summary:')+1:]

In [140]:
soc

['- A and B are friends who have recently broken up, and they are both struggling to deal with the emotional fallout. They still have feelings for each other, but they are trying to move on. The conversation is filled with expressions of anger, sadness, and hurt, but there are also a few brief instances of positivity. Overall, the sentiment of the conversation is mostly negative.']

In [130]:
li = ['Relationship:', '- Friends who have broken up recently.', '- They still have feelings for each other, but are trying to move on.', '', 'Character of A:', '- Emotional and impulsive: Expresses intense emotions throughout the conversation.', '- Determined to move on from the relationship: Repeatedly says "bye" and tries to cut off communication.', '- Has difficulty controlling their emotions: Uses strong language, like "vey" and "illa" to express anger and frustration.', '- Tries to maintain a friendly relationship: Uses terms of endearment, like "jyo baby" and "my baby", even after the breakup.', '', 'Character of B:', '- Tries to remain calm and rational: Often responds with short, simple answers or emojis.', '- Willing to work on the relationship: Suggests meeting up or communicating to resolve their issues.', '- Feels hurt and confused by the breakup: Asks "Em sambandham ledhu" (What is our relationship now?) and "Endhuku baby ala antav" (Why are you calling me baby?).', '- Tries to maintain a friendly relationship: Also uses terms of endearment, like "naanna" and "prashu baabu", even after the breakup.', '', 'Sentiment Analysis:', '- Mostly negative: The conversation is filled with expressions of anger, sadness, and hurt.', '- Some positive moments: There are a few brief instances of positivity, such as when they reminisce about happy memories.', '', 'Summary:', '- A and B are friends who have recently broken up, and they are both struggling to deal with the emotional fallout. They still have feelings for each other, but they are trying to move on. The conversation is filled with expressions of anger, sadness, and hurt, but there are also a few brief instances of positivity. Overall, the sentiment of the conversation is mostly negative.']

In [62]:
def preprocess(data):
    if((data.count('am')>10 and data.count('pm')>10) or (data.count('AM')>10 and data.count('PM')>10)):
        pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern
    else:
        pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr 
    messages = re.split(pattern,data)[1:]
    dates = re.findall(pattern,data)
    df = pd.DataFrame({'user_message':messages, 'message_date':dates})
    for i in range(len(df)):
        if('<This Message Was Edited>' in df.loc[i]['user_message']):
            df.loc[i]['user_message'] = df.loc[i]['user_message'].replace('<This Message Was Edited>','')
        if('\n' in df.loc[i]['user_message']):
            df.loc[i]['user_message'] = df.loc[i]['user_message'].replace("\n",'')
        if(':' not in df.loc[i]['user_message'] or  '<Media omitted>' in df.loc[i]['user_message'] or  'null' in df.loc[i]['user_message'] or 'http' in df.loc[i]['user_message'] or 'This message was deleted' in df.loc[i]['user_message']):
            df.drop(i,inplace=True)
    df = df.reset_index(drop=True)
    users = []
    messages = [] 
    for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1: ]:
            users.append(entry[1])
            messages.append(entry[2])
    df = df.reset_index(drop=True)
    if(len(df)!=len(users)):
        users = users[:len(df)]
        messages = messages[:len(df)]
    df['users'] = users 
    df['messages'] = messages
    df  = df.drop('user_message',axis=1)
    person1 = df.users.unique()[0]
    person2 = df.users.unique()[1]
    for i in range(len(df)):
        if df.loc[i]['users'] == person1:
            df.loc[i]['users'] = 'A'
        elif df.loc[i]['users'] == person2:
            df.loc[i]['users'] = 'B'
    chat = []
    for i in range(len(df)):
        chat.append(df.loc[i]['users']+' :   '+df.loc[i]['messages'])
    return person1,person2,chat

In [81]:
f = open("/home/user/Documents/GENARATIVE_AI/WHAT'SAPP _CHAT_ANALYZER/dataset/WhatsApp Chat with Sahithi Dad.txt",'r',encoding='utf-8')

In [82]:
data = f.read()

In [83]:
person1,person2,chat = preprocess(data)

/tmp/ipykernel_77923/778483354.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[i]['users'] = 'A'
/tmp/ipykernel_77923/778483354.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[i]['users'] = 'B'

In [84]:
len(chat)

346

In [85]:
person1

'ysrfoundation2'

In [86]:
person2

'Sahithi Dad'

In [1]:
# pandas
# numpy
# streamlit
# emoji
# urlextract
# matplotlib
# wordcloud
# stop_words
# google-generativeai
# python-dotenv
# regex    
# seaborn
# ipykern

In [2]:
import pandas as pd
import re

In [3]:
def preprocess2(data):
    if((data.count('am')>10 and data.count('pm')>10) or (data.count('AM')>10 and data.count('PM')>10)):
        pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern
    else:
        pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr 
    messages = re.split(pattern,data)[1:]
    dates = re.findall(pattern,data)
    df = pd.DataFrame({'user_message':messages, 'message_date':dates})
    df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %H:%M - ')
    df.rename(columns={'message_date':'date'}, inplace=True)
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month_name()
    df['day'] = df['date'].dt.day
    df['hour'] = df['date'].dt.hour
    df['minute'] = df['date'].dt.minute
    users = []
    messages = [] 
    for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1: ]:
            users.append(entry[1])
            messages.append(entry[2])
        else:
            users.append('group_notification')
            messages.append(entry[0])
    df['users'] = users

In [6]:
f = open('dataset/WhatsApp Chat with Sahithi Dad.txt','r',encoding='utf-8')

In [7]:
data = f.read()

In [8]:
if((data.count('am')>10 and data.count('pm')>10) or (data.count('AM')>10 and data.count('PM')>10)):
        pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern
else:
    pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr

In [9]:
messages = re.split(pattern,data)[1:]
dates = re.findall(pattern,data)

In [10]:
df = pd.DataFrame({'user_message':messages, 'message_date':dates})

In [12]:
df.head()

                                        user_message            message_date
0  Messages and calls are end-to-end encrypted. N...  30/11/2023, 7:44 am -
1                              ysrfoundation2: Hii\n  30/11/2023, 7:45 am -
2                                 Sahithi Dad: Hlo\n  30/11/2023, 7:49 am -
3                             ysrfoundation2: Hiii\n  03/12/2023, 1:34 pm -
4                          ysrfoundation2: Sahithi\n  03/12/2023, 1:52 pm -

In [15]:
# df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %H:%M - ')
# df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %I:%M %p - ')
df['message_date'] = pd.to_datetime(df['message_date'], format='%d/%m/%Y, %I:%M %p - ')

In [16]:
df.head()

                                        user_message        message_date
0  Messages and calls are end-to-end encrypted. N... 2023-11-30 07:44:00
1                              ysrfoundation2: Hii\n 2023-11-30 07:45:00
2                                 Sahithi Dad: Hlo\n 2023-11-30 07:49:00
3                             ysrfoundation2: Hiii\n 2023-12-03 13:34:00
4                          ysrfoundation2: Sahithi\n 2023-12-03 13:52:00

In [17]:
f = open('dataset/WhatsApp Chat with Jyo👀🔥.....txt','r',encoding='utf-8')

In [18]:
data = f.read()

In [19]:
if((data.count('am')>10 and data.count('pm')>10) or (data.count('AM')>10 and data.count('PM')>10)):
        pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern
else:
    pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr

In [20]:
messages = re.split(pattern,data)[1:]
dates = re.findall(pattern,data)

In [21]:
df = pd.DataFrame({'user_message':messages, 'message_date':dates})

In [22]:
df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %H:%M - ')

In [23]:
df.head()

                                        user_message        message_date
0  Messages and calls are end-to-end encrypted. N... 2023-09-05 21:29:00
1          Naga Siva Sai Prasanth: <Media omitted>\n 2023-09-09 01:07:00
2          Naga Siva Sai Prasanth: <Media omitted>\n 2023-09-09 01:19:00
3                       Jyo👀🔥....: <Media omitted>\n 2023-09-09 22:29:00
4                       Jyo👀🔥....: <Media omitted>\n 2023-09-12 01:23:00

In [36]:
import warnings as warn
warn.filterwarnings("ignore")

In [81]:
preprocess2(data)

,date,year,month,day,hour,minute,users,messages
0,2023-09-05 21:29:00,2023,September,5,21,29,Naga Siva Sai Prasanth,<Media omitted>\n
1,2023-09-09 01:07:00,2023,September,9,1,7,Naga Siva Sai Prasanth,<Media omitted>\n
2,2023-09-09 01:19:00,2023,September,9,1,19,Jyo👀🔥....,<Media omitted>\n
3,2023-09-09 22:29:00,2023,September,9,22,29,Jyo👀🔥....,<Media omitted>\n
4,2023-09-12 01:23:00,2023,September,12,1,23,Jyo👀🔥....,<Media omitted>\n
...,...,...,...,...,...,...,...,...
380,2023-12-28 21:14:00,2023,December,28,21,14,Naga Siva Sai Prasanth,En\n
381,2023-12-28 21:16:00,2023,December,28,21,16,Naga Siva Sai Prasanth,Em vacation\n
382,2023-12-28 21:16:00,2023,December,28,21,16,Naga Siva Sai Prasanth,Mari\n
383,2023-12-28 21:16:00,2023,December,28,21,16,Naga Siva Sai Prasanth,Naa kosamu ani sollu\n
384,2023-12-28 21:16:00,2023,December,28,21,16,Naga Siva Sai Prasanth,Chepavu\n

In [122]:
import pandas as pd
import warnings as warn 
import re
from aider import get_response
warn.filterwarnings("ignore")

def preprocess1(data):
    if((data.count('am')>10 and data.count('pm')>10) or (data.count('AM')>10 and data.count('PM')>10)):
        pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern
    else:
        pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr 
    messages = re.split(pattern,data)[1:]
    dates = re.findall(pattern,data)
    df = pd.DataFrame({'user_message':messages, 'message_date':dates})
    for i in range(len(df)):
        if('<This Message Was Edited>' in df.loc[i]['user_message']):
            df.at[i,'user_message'] = df.loc[i]['user_message'].replace('<This Message Was Edited>','')
        if('\n' in df.loc[i]['user_message']):
            df.at[i,'user_message'] = df.loc[i]['user_message'].replace("\n",'')
        if(':' not in df.loc[i]['user_message'] or  '<Media omitted>' in df.loc[i]['user_message'] or  'null' in df.loc[i]['user_message'] or 'http' in df.loc[i]['user_message'] or 'This message was deleted' in df.loc[i]['user_message']):
            df.drop(i,inplace=True)
    df = df.reset_index(drop=True)
    users = []
    messages = [] 
    for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1: ]:
            users.append(entry[1])
            messages.append(entry[2])
    df = df.reset_index(drop=True)
    if(len(df)<len(users)):
        users = users[:len(df)]
        messages = messages[:len(df)]
    else: 
        df = df[:len(users)]
    df['users'] = users 
    df['messages'] = messages
    df  = df.drop('user_message',axis=1)
    person1 = df.users.unique()[0]
    person2 = df.users.unique()[1]
    for i in range(len(df)):
        if df.loc[i]['users'] == person1:
            df.at[i,'users'] = 'A'
        elif df.loc[i]['users'] == person2:
            df.at[i,'users'] = 'B'
    chat = []
    for i in range(len(df)):
        chat.append(df.loc[i]['users']+' :   '+df.loc[i]['messages'])
    return person1,person2,chat

def preprocess2(data):
    if((data.count('am')>10 and data.count('pm')>10) or (data.count('AM')>10 and data.count('PM')>10)):
        pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern
        if (data.count('am')>10 and data.count('pm')>10):
            format = '%d/%m/%Y, %I:%M %p - '
        else: 
            format = '%m/%d/%y, %I:%M %p - '

    else:
        pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr 
        format='%m/%d/%y, %H:%M - '
    messages = re.split(pattern,data)[1:]
    dates = re.findall(pattern,data)
    df = pd.DataFrame({'user_message':messages, 'message_date':dates})
    df['message_date'] = pd.to_datetime(df['message_date'], format=format)
    df.rename(columns={'message_date':'date'}, inplace=True)
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month_name()
    df['day'] = df['date'].dt.day
    df['hour'] = df['date'].dt.hour
    df['minute'] = df['date'].dt.minute
    for i in range(len(df)):
        if('<This Message Was Edited>' in df.loc[i]['user_message']):
            df.at[i,'user_message'] = df.loc[i]['user_message'].replace('<This Message Was Edited>','')
        if('\n' in df.loc[i]['user_message']):
            df.at[i,'user_message'] = df.loc[i]['user_message'].replace("\n",'')
    users = []
    messages = [] 
    for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1: ]:
            users.append(entry[1])
            messages.append(entry[2])
    if(len(df)<len(users)):
        users = users[:len(df)]
        messages = messages[:len(df)]
    else: 
        df = df[:len(users)]
    df['users'] = users 
    df['messages'] = messages
    df = df.drop('user_message',axis=1)
    return df

In [130]:
f = open('dataset/WhatsApp Chat with Sahithi Dad.txt','r',encoding='utf-8')

In [131]:
data = f.read()

In [134]:
preprocess2(data)

,date,year,month,day,hour,minute,users,messages
0,2023-11-30 07:44:00,2023,November,30,7,44,ysrfoundation2,Hii
1,2023-11-30 07:45:00,2023,November,30,7,45,Sahithi Dad,Hlo
2,2023-11-30 07:49:00,2023,November,30,7,49,ysrfoundation2,Hiii
3,2023-12-03 13:34:00,2023,December,3,13,34,ysrfoundation2,Sahithi
4,2023-12-03 13:52:00,2023,December,3,13,52,ysrfoundation2,What are you doing
...,...,...,...,...,...,...,...,...
454,2024-01-07 20:40:00,2024,January,7,20,40,Sahithi Dad,Ame
455,2024-01-07 20:42:00,2024,January,7,20,42,ysrfoundation2,Arey EDI accident naku estam raa ee movie lo
456,2024-01-07 21:07:00,2024,January,7,21,7,ysrfoundation2,https://youtube.com/shorts/GM1tIe2jD-c?si=M_eh...
457,2024-01-10 18:14:00,2024,January,10,18,14,ysrfoundation2,<Media omitted>
458,2024-01-10 18:54:00,2024,January,10,18,54,ysrfoundation2,Naa kallu Edo chepuko

In [138]:
from urlextract import URLExtract
from collections import Counter
from wordcloud import WordCloud
from datetime import datetime
import string
import emoji
import re
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from stop_words import get_stop_words
import pathlib
import textwrap
import os
from dotenv import load_dotenv
from IPython.display import display
from IPython.display import Markdown
import google.generativeai as genai


load_dotenv()
genai.configure(api_key = os.getenv('GOOGLE_API_KEY'))

stopwords = get_stop_words('en')
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F700-\U0001F77F"  # alchemical symbols
                           u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                           u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                           u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                           u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                           u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                           u"\U00002702-\U000027B0"  # Dingbats
                           u"\U000024C2-\U0001F251"  
                           "]+", flags=re.UNICODE)

emojis = []
messages = []

In [156]:
def fetch_chat_stats(df):
    emoji = [emoji_pattern.findall(msg) for msg in df['messages']]
    global emojis
    global messages
    for moj in emoji:
        if(len(moj)>=1):
            li = []
            for i in range(len(moj)):
                for obj in moj[i]:
                    li.append(obj)
            moj = li
        emojis.extend(moj)  
    emojis = [emoji for emoji in emojis if emoji != '️']
    num_messages = len(df)
    words = [word for msg in df['messages'] for word in msg.split() if msg != '<Media omitted>\n' and word not in emojis and word not in string.punctuation]
    word_counts = Counter(words)
    word_counts = dict(sorted(word_counts.items(), key=lambda item: item[1], reverse=True))
    num_words = len(words)
    num_media = len(df[df['messages']=='<Media omitted>'])
    num_emojis = len(emojis)
    emoji_counts = Counter(emojis)
    emoji_counts = dict(sorted(emoji_counts.items(), key=lambda item: item[1], reverse=True))
    extractor = URLExtract()
    num_urls = len([extractor.find_urls(msg) for msg in  list(df['messages']) if len(extractor.find_urls(msg))!=0])
    messages = [msg for msg in df['messages'] if '<Media omitted>' not in msg and 'null' not in msg and 'This message was deleted' not in msg]
    print(messages)
    return num_messages,num_words,num_media,num_urls,num_emojis

In [140]:
df = preprocess2(data)

In [157]:
fetch_chat_stats(df)

['Hii', 'Hlo', 'Hiii', 'Sahithi', 'What are you doing', 'Ntg', 'Ra', 'Am ayna telisinda', 'Ledhu sir chuda lee anta', 'Avunaa', 'Hmm', 'Burra paadu', 'Asalu', 'Sahithi pottidi ki msg cheyu raa', 'Haa', 'Yevariki', 'Chellu kaa', 'Mi head ki', 'Haa', 'Na gubalu yegara gottey galadu le', '🤣🤣🤣', 'Sare tinnava', 'Haa', 'Nuvvo', 'Call cheyyamane vadiki', 'Vadhu', 'Le', 'Ledhu time chusava', 'Hoo', 'Ade chepthunna', 'Hmm', 'Ohh', 'Ledu ledu', 'Hoo', 'Inkante', 'Burra paadu', 'Kadupula noppi', 'Yeh visyam clarity ga telidhu', 'Chi', 'Am clg yeh babu', 'Manadu', 'Manadi', 'Haa same feeling kani chepa lenu', '😢', 'Sare Lee vadu reply Este niku msg chesta lee', 'Kk', 'Padmavathi clg kuda selavu', 'Hoo appude adige sava', 'Fast nenu', 'Selavu manaki kuda', 'Tomorrow (05.12.23) college holiday', 'S', 'Super', 'Am antha badha', 'Arey maa Chelli pettamandi petta', 'Niku badha ante CLG tmrw holiday estaro ledho ani', 'Nakaa', 'Ledhu naku ani pettali kani mistake', 'Ohh', 'Me chelli ki echara', 'Selavu', 'Haa', 'Hi', 'Chadivesava', 'Ledhu', 'Tmrw holiday estaro amo ani balance uncha', 'Evvaru mari', 'Hoo sare evvaku pothe ledhu', 'Ante', 'Jyothi akka vallu bojanam ki pilichara meku', 'Epudu', 'Repu', 'Emo naku telidhu', 'Me mummy ki adigi cheppu', 'Sare kani', 'Nuvvu chadesava', 'Ledu ra', 'Bayam vesthundi', 'Naku', 'Hoo', 'Haaa', 'Send me', 'Today', 'Holiday', 'Msg chudu grouplo', 'Hoo super raa', 'Orey', 'Bojanalaki vasthava', 'Shake', 'Hiii', 'Tinnava', 'Hi', 'Hiii', 'Hlo', 'Aishu', '💯', '😍😍', 'Nice', '😚😚', 'Shop now on Meesho! https://www.meesho.com/s/p/4w7qta?utm_source=s_w', 'https://youtu.be/nZqD1FyXdBE?si=LgG8tjA9U4orjAjz', 'Arey EDI oka sari chudu', 'Ila vuntundi aa', 'Haa', 'Epudu Mari pondi', 'Enti', 'Pondi enti ra', 'Epudu Mari poindhi  raa', 'Baledu antunnava', 'Ma intlo chala long antunnaru', 'Ledhu raa super ga chesaru antunna', 'Hoo', 'Avunu', 'Emo time undi kadha chudam', 'Haa sare le', 'Hmm', 'Arey balloons ne phone lo order cheyu raa', 'Epudu cheste aapudo vastadi', 'Na phone lo nenu yeppudu pettaledu ra', 'Ne phone lo petti money kavalante echestha', 'Aishu ma nanna money adigaru ra', 'Arey 350 ani chepamannadi taruvata chudam annadu', 'Ok na', 'Yevaru', 'Ma mom', 'Adi kaadu yeh babu', 'Mari enti', 'Cheppuluvi, kit vi', 'Enti ardham kaledhu', 'Phone cheyyala', 'Cheppulu', 'Baby kit usha valla babu ki teesukunnam kada', 'Aa money', 'Haa sare', 'Nenu raanu ra', 'Em', 'Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru', 'Hoo', 'Haaa', 'Sare kani money anta', '280 ra', 'Monna 50 icha annav kada', '230', 'Haa kk', 'Haa sare', '🙏🏻', 'Y', 'Song baledha', 'Super', 'Anduke petta reasons em ledhu', 'Aishu pettava photo', 'Enti ra', 'Hii sahithi', 'Hi ra', 'Photo pettava', 'Haa pedata lee', 'Sry raledu endhuku ante dress change cheyledu', 'Andhuke', 'Paravaledu lee', 'Akhila kavi vacharu', 'Marchipoku e roju pettu', 'Avunaa', 'Haa', 'Videos pettu', 'Naku', 'Puja vi', 'Haa', 'Aishu pettava', 'Photo', 'Haa', 'Am annaru', 'Oley hd vi pettamani cheppa kadey', '\U0001fae2', 'Hi', 'Hii', 'Chadivesava madam', 'Ledhu raa maths main chudali', 'Chusava mari', 'You deleted this message', 'Chadivesava', 'Ledhu', 'Nv brilliant le appudu kappudu ayna chusi rasesthav', 'Haa avunu lee', 'Yes its true', 'Aishu e question chadivava', 'Nanu asalu em chadavale', 'Avunaa', 'Sare le', 'Hmm', 'Send me', 'Aishu', 'Adigava', 'Vallaki  am annaru', 'Avariki', 'Anu monika mani vallaki', 'Haa kk moni , rama', 'Anu kudha m avvaka pote  annadi', 'Hii', 'Hii', 'Hi', 'Hiii', 'Am doing', 'Hiii', 'Hi', 'Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa', 'Rama raadhu aa', 'Ante mrng varuku telidhu', 'Am alaga', 'Emo', 'Avuna', 'Hmm', 'Inko 4members yevaru ra', 'Chinnamudu , paiga vallu avaro anta family nee', 'Ohh kk le', 'Hmm', 'Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali', 'Sare', 'Sare inka', 'Cheppali', 'Ante tmrw kosam adaina cheppu', 'Games aa', 'Haa', 'Okka 5min aaagu', 'Msg chesthanu', 'Kk', 'Yeh dress vesthav', 'Nenu birthday di anukuntunna u', 'Avunaa', 'Hmm', 'Mari nenu am veyyali', 'Authe', 'Emo nuvve Alo chinchu', 'Cheppu nuvvu', 'Naku ala telustunndi', 'Na dresslu anni chusav kada', 'Emo raa nuvve decide avvu', 'Sare le', 'Edi ok naa', 'Haa kk', 'Kk le', 'Hmm', 'Leka pothe inko top vundi', 'Ado', 'Kothadi adi ayna vadesthanu le', 'Haa ne estam nee dress', 'Sare le', 'Hmm', 'Inkem games adugu mani vallaki', 'Hiii sahi', 'Anu ki phone cheyu oka sari adugu', 'Sare', 'Hi', 'Enni gantalaki ra', 'Aishu phone pay number pettu money phone pay chestha', '9949437849', 'Kk naa', 'Kk', 'Orey phone pay maadi avvatledu limit aypoyindi madi e roju di', 'Mrng thechi echesthanu me daddy ki cheppu', 'Kk', 'Evena pics mari levaa', 'Haa rassu ki cheppa', 'Tana daggara konni vunnay', 'Oka sari nuvvu msg pettu', 'Kk', 'Hi', 'Hiii', 'https://www.instagram.com/reel/C1J_HW6pjTb/?igsh=N2ZiNzVhMjY2OA==', '🤣🤣', '😂', 'Date chusava', 'Sahithi nee English key nadaggara vundi', 'Ade vethika', 'Chala sepu', 'Hoo nenu epudo msg petta', 'Mobile vundadu ani telusu gaa neku', '12th answer pettava', 'Tqqq❤️😘🥰', 'Abho chalu lee', '😄', 'Open chesava', 'Set', 'Haa chusa', 'Pump evvale ante', 'Anni kk', 'Evvaleda pump', 'Ledhu', 'Kkk', 'https://youtube.com/shorts/Ze8DjY_4kVQ?si=CXBIMqJh3p7cPOzm', 'Aishu', 'Aishu', 'Photo pettu', 'Aa photo', 'Frame', 'Pack chesadhu vadu', 'Avuna', 'Nv kuda chudaledha', 'Hmm', 'Ledhu', 'Indhaka yekkadiki vellav', 'Gift kosam aa', 'Sorry wrong answer pakodi kosam', 'Avunaa', 'Hmm', 'Gift konta annav', 'Haa tmrw suprise miku ,anu ki kudha', 'Nku cheppu le', 'Parledu', 'Tmrw chustav kadha', 'Cheppu', 'Ra', 'Bye muggulu chustunna', 'Cheppava', 'Anthe n', 'Nenu neku telisinatte chesa ga yedi chesinaa', 'Edi cheating asalu', 'Ledhu raa inka em konalo decide avvale anduke', 'Avunaa', 'Hmm', 'Aishu', 'Aishu chude yelaga chesado', 'Chala kopam ga vundi vaadi medha', 'Haa delete kudha cheya lee', 'Cheyyadu vaadu nku telusu', 'Haa Mari em chestam nenu , nuvvu kudha chudale', 'Hmm', 'Arey cake kosam money enta', 'Cheppa lee', 'Sare anu status chusava', 'Me estham yeh', 'Vaadu inka delete cheyleda', 'Naku chala chiraku ga vundi', 'Anu kuda status pettisindi', 'Vinu', 'Aishu', 'Tmrw chemistry bullet evvu', 'https://www.instagram.com/reel/C1i2zXhp-En/?igsh=MWp4bDQ1MmhxemtyOQ==', 'Arey msg cheyu tanuja ki', 'Plss', 'Kk', 'Arey manam Ela nee epudaina photos tesukundam kk naa', 'Done done 👍👍👍', 'Sare chemistry photos pettu', 'Ammo chadivedham ane', 'Haa kani epudu di ee paper', 'Repatiki', 'Hiiii', 'Hi', 'Ame', 'Arey EDI accident naku estam raa ee movie lo', 'https://youtube.com/shorts/GM1tIe2jD-c?si=M_ehiKgESYV0vU7F', 'Naa kallu Edo chepuko']

(459, 1149, 100, 6, 176)

In [158]:
messages

['Hii',
 'Hlo',
 'Hiii',
 'Sahithi',
 'What are you doing',
 'Ntg',
 'Ra',
 'Am ayna telisinda',
 'Ledhu sir chuda lee anta',
 'Avunaa',
 'Hmm',
 'Burra paadu',
 'Asalu',
 'Sahithi pottidi ki msg cheyu raa',
 'Haa',
 'Yevariki',
 'Chellu kaa',
 'Mi head ki',
 'Haa',
 'Na gubalu yegara gottey galadu le',
 '🤣🤣🤣',
 'Sare tinnava',
 'Haa',
 'Nuvvo',
 'Call cheyyamane vadiki',
 'Vadhu',
 'Le',
 'Ledhu time chusava',
 'Hoo',
 'Ade chepthunna',
 'Hmm',
 'Ohh',
 'Ledu ledu',
 'Hoo',
 'Inkante',
 'Burra paadu',
 'Kadupula noppi',
 'Yeh visyam clarity ga telidhu',
 'Chi',
 'Am clg yeh babu',
 'Manadu',
 'Manadi',
 'Haa same feeling kani chepa lenu',
 '😢',
 'Sare Lee vadu reply Este niku msg chesta lee',
 'Kk',
 'Padmavathi clg kuda selavu',
 'Hoo appude adige sava',
 'Fast nenu',
 'Selavu manaki kuda',
 'Tomorrow (05.12.23) college holiday',
 'S',
 'Super',
 'Am antha badha',
 'Arey maa Chelli pettamandi petta',
 'Niku badha ante CLG tmrw holiday estaro ledho ani',
 'Nakaa',
 'Ledhu naku ani pettali kani mistake',
 'Ohh',
 'Me chelli ki echara',
 'Selavu',
 'Haa',
 'Hi',
 'Chadivesava',
 'Ledhu',
 'Tmrw holiday estaro amo ani balance uncha',
 'Evvaru mari',
 'Hoo sare evvaku pothe ledhu',
 'Ante',
 'Jyothi akka vallu bojanam ki pilichara meku',
 'Epudu',
 'Repu',
 'Emo naku telidhu',
 'Me mummy ki adigi cheppu',
 'Sare kani',
 'Nuvvu chadesava',
 'Ledu ra',
 'Bayam vesthundi',
 'Naku',
 'Hoo',
 'Haaa',
 'Send me',
 'Today',
 'Holiday',
 'Msg chudu grouplo',
 'Hoo super raa',
 'Orey',
 'Bojanalaki vasthava',
 'Shake',
 'Hiii',
 'Tinnava',
 'Hi',
 'Hiii',
 'Hlo',
 'Aishu',
 '💯',
 '😍😍',
 'Nice',
 '😚😚',
 'Shop now on Meesho! https://www.meesho.com/s/p/4w7qta?utm_source=s_w',
 'https://youtu.be/nZqD1FyXdBE?si=LgG8tjA9U4orjAjz',
 'Arey EDI oka sari chudu',
 'Ila vuntundi aa',
 'Haa',
 'Epudu Mari pondi',
 'Enti',
 'Pondi enti ra',
 'Epudu Mari poindhi  raa',
 'Baledu antunnava',
 'Ma intlo chala long antunnaru',
 'Ledhu raa super ga chesaru antunna',
 'Hoo',
 'Avunu',
 'Emo time undi kadha chudam',
 'Haa sare le',
 'Hmm',
 'Arey balloons ne phone lo order cheyu raa',
 'Epudu cheste aapudo vastadi',
 'Na phone lo nenu yeppudu pettaledu ra',
 'Ne phone lo petti money kavalante echestha',
 'Aishu ma nanna money adigaru ra',
 'Arey 350 ani chepamannadi taruvata chudam annadu',
 'Ok na',
 'Yevaru',
 'Ma mom',
 'Adi kaadu yeh babu',
 'Mari enti',
 'Cheppuluvi, kit vi',
 'Enti ardham kaledhu',
 'Phone cheyyala',
 'Cheppulu',
 'Baby kit usha valla babu ki teesukunnam kada',
 'Aa money',
 'Haa sare',
 'Nenu raanu ra',
 'Em',
 'Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru',
 'Hoo',
 'Haaa',
 'Sare kani money anta',
 '280 ra',
 'Monna 50 icha annav kada',
 '230',
 'Haa kk',
 'Haa sare',
 '🙏🏻',
 'Y',
 'Song baledha',
 'Super',
 'Anduke petta reasons em ledhu',
 'Aishu pettava photo',
 'Enti ra',
 'Hii sahithi',
 'Hi ra',
 'Photo pettava',
 'Haa pedata lee',
 'Sry raledu endhuku ante dress change cheyledu',
 'Andhuke',
 'Paravaledu lee',
 'Akhila kavi vacharu',
 'Marchipoku e roju pettu',
 'Avunaa',
 'Haa',
 'Videos pettu',
 'Naku',
 'Puja vi',
 'Haa',
 'Aishu pettava',
 'Photo',
 'Haa',
 'Am annaru',
 'Oley hd vi pettamani cheppa kadey',
 '\U0001fae2',
 'Hi',
 'Hii',
 'Chadivesava madam',
 'Ledhu raa maths main chudali',
 'Chusava mari',
 'You deleted this message',
 'Chadivesava',
 'Ledhu',
 'Nv brilliant le appudu kappudu ayna chusi rasesthav',
 'Haa avunu lee',
 'Yes its true',
 'Aishu e question chadivava',
 'Nanu asalu em chadavale',
 'Avunaa',
 'Sare le',
 'Hmm',
 'Send me',
 'Aishu',
 'Adigava',
 'Vallaki  am annaru',
 'Avariki',
 'Anu monika mani vallaki',
 'Haa kk moni , rama',
 'Anu kudha m avvaka pote  annadi',
 'Hii',
 'Hii',
 'Hi',
 'Hiii',
 'Am doing',
 'Hiii',
 'Hi',
 'Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa',
 'Rama raadhu aa',
 'Ante mrng varuku telidhu',
 'Am alaga',
 'Emo',
 'Avuna',
 'Hmm',
 'Inko 4members yevaru ra',
 'Chinnamudu , paiga vallu avaro anta family nee',
 'Ohh kk le',
 'Hmm',
 'Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali',
 'Sare',
 'Sare inka',
 'Cheppali',
 'Ante tmrw kosam adaina cheppu',
 'Games aa',
 'Haa',
 'Okka 5min aaagu',
 'Msg chesthanu',
 'Kk',
 'Yeh dress vesthav',
 'Nenu birthday di anukuntunna u',
 'Avunaa',
 'Hmm',
 'Mari nenu am veyyali',
 'Authe',
 'Emo nuvve Alo chinchu',
 'Cheppu nuvvu',
 'Naku ala telustunndi',
 'Na dresslu anni chusav kada',
 'Emo raa nuvve decide avvu',
 'Sare le',
 'Edi ok naa',
 'Haa kk',
 'Kk le',
 'Hmm',
 'Leka pothe inko top vundi',
 'Ado',
 'Kothadi adi ayna vadesthanu le',
 'Haa ne estam nee dress',
 'Sare le',
 'Hmm',
 'Inkem games adugu mani vallaki',
 'Hiii sahi',
 'Anu ki phone cheyu oka sari adugu',
 'Sare',
 'Hi',
 'Enni gantalaki ra',
 'Aishu phone pay number pettu money phone pay chestha',
 '9949437849',
 'Kk naa',
 'Kk',
 'Orey phone pay maadi avvatledu limit aypoyindi madi e roju di',
 'Mrng thechi echesthanu me daddy ki cheppu',
 'Kk',
 'Evena pics mari levaa',
 'Haa rassu ki cheppa',
 'Tana daggara konni vunnay',
 'Oka sari nuvvu msg pettu',
 'Kk',
 'Hi',
 'Hiii',
 'https://www.instagram.com/reel/C1J_HW6pjTb/?igsh=N2ZiNzVhMjY2OA==',
 '🤣🤣',
 '😂',
 'Date chusava',
 'Sahithi nee English key nadaggara vundi',
 'Ade vethika',
 'Chala sepu',
 'Hoo nenu epudo msg petta',
 'Mobile vundadu ani telusu gaa neku',
 '12th answer pettava',
 'Tqqq❤️😘🥰',
 'Abho chalu lee',
 '😄',
 'Open chesava',
 'Set',
 'Haa chusa',
 'Pump evvale ante',
 'Anni kk',
 'Evvaleda pump',
 'Ledhu',
 'Kkk',
 'https://youtube.com/shorts/Ze8DjY_4kVQ?si=CXBIMqJh3p7cPOzm',
 'Aishu',
 'Aishu',
 'Photo pettu',
 'Aa photo',
 'Frame',
 'Pack chesadhu vadu',
 'Avuna',
 'Nv kuda chudaledha',
 'Hmm',
 'Ledhu',
 'Indhaka yekkadiki vellav',
 'Gift kosam aa',
 'Sorry wrong answer pakodi kosam',
 'Avunaa',
 'Hmm',
 'Gift konta annav',
 'Haa tmrw suprise miku ,anu ki kudha',
 'Nku cheppu le',
 'Parledu',
 'Tmrw chustav kadha',
 'Cheppu',
 'Ra',
 'Bye muggulu chustunna',
 'Cheppava',
 'Anthe n',
 'Nenu neku telisinatte chesa ga yedi chesinaa',
 'Edi cheating asalu',
 'Ledhu raa inka em konalo decide avvale anduke',
 'Avunaa',
 'Hmm',
 'Aishu',
 'Aishu chude yelaga chesado',
 'Chala kopam ga vundi vaadi medha',
 'Haa delete kudha cheya lee',
 'Cheyyadu vaadu nku telusu',
 'Haa Mari em chestam nenu , nuvvu kudha chudale',
 'Hmm',
 'Arey cake kosam money enta',
 'Cheppa lee',
 'Sare anu status chusava',
 'Me estham yeh',
 'Vaadu inka delete cheyleda',
 'Naku chala chiraku ga vundi',
 'Anu kuda status pettisindi',
 'Vinu',
 'Aishu',
 'Tmrw chemistry bullet evvu',
 'https://www.instagram.com/reel/C1i2zXhp-En/?igsh=MWp4bDQ1MmhxemtyOQ==',
 'Arey msg cheyu tanuja ki',
 'Plss',
 'Kk',
 'Arey manam Ela nee epudaina photos tesukundam kk naa',
 'Done done 👍👍👍',
 'Sare chemistry photos pettu',
 'Ammo chadivedham ane',
 'Haa kani epudu di ee paper',
 'Repatiki',
 'Hiiii',
 'Hi',
 'Ame',
 'Arey EDI accident naku estam raa ee movie lo',
 'https://youtube.com/shorts/GM1tIe2jD-c?si=M_ehiKgESYV0vU7F',
 'Naa kallu Edo chepuko']

In [159]:
emojis

['🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍',
 '🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍',
 '🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍',
 '🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍',
 '🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍',
 '🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍',
 '🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍',
 '🤣',
 '🤣',
 '🤣',
 '😢',
 '💯',
 '😍',
 '😍',
 '😚',
 '😚',
 '🙏',
 '🏻',
 '\U0001fae2',
 '🤣',
 '🤣',
 '😂',
 '❤',
 '😘',
 '🥰',
 '😄',
 '👍',
 '👍',
 '👍']

In [160]:
def fetch_wordcloud():
    global messages
    print(len(messages))
    text = ' '.join(messages)
    wordcloud = WordCloud(width=800, height=800, background_color='white', stopwords=set(stopwords)).generate(text)
    plt.figure(figsize=(8, 8))
    plt.imshow(wordcloud)
    plt.axis("off")
    plt.tight_layout(pad=0)
    plotpath = "word_cloud.png"
    plt.savefig(plotpath)
    plt.close()
    return plotpath

In [161]:
fetch_wordcloud()

352

'word_cloud.png'